const Database = require('better-sqlite3');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const uid = () => crypto.randomUUID();
const now = () => new Date().toISOString();

class DatabaseService {
  constructor(file, migrationsDir) { this.file=file; this.migrationsDir=migrationsDir; this.open(); }
  open(){ this.db=new Database(this.file); this.db.pragma('foreign_keys = ON'); this.db.pragma('journal_mode = WAL'); }
  migrate() {
    this.db.exec('CREATE TABLE IF NOT EXISTS schema_migrations (version TEXT PRIMARY KEY, applied_at TEXT NOT NULL)');
    const done = new Set(this.db.prepare('SELECT version FROM schema_migrations').all().map(x=>x.version));
    for (const file of fs.readdirSync(this.migrationsDir).filter(x=>x.endsWith('.sql')).sort()) {
      if (done.has(file)) continue;
      const sql=fs.readFileSync(path.join(this.migrationsDir,file),'utf8');
      const tx=this.db.transaction(()=>{ this.db.exec(sql); this.db.prepare('INSERT INTO schema_migrations(version,applied_at) VALUES (?,?)').run(file,now()); }); tx();
    }
  }
  audit(entity,id,action,before,after){ this.db.prepare('INSERT INTO audit_log(id,entity_type,entity_id,action,before_json,after_json,created_at) VALUES(?,?,?,?,?,?,?)').run(uid(),entity,id,action,before?JSON.stringify(before):null,after?JSON.stringify(after):null,now()); }
  dashboardSummary(){ const one=(sql)=>this.db.prepare(sql).get().n; return {assets:one('SELECT COUNT(*) n FROM asset WHERE deleted_at IS NULL'),available:one("SELECT COUNT(*) n FROM asset WHERE deleted_at IS NULL AND status='AVAILABLE'"),usageOpen:one("SELECT COUNT(*) n FROM usage_request WHERE deleted_at IS NULL AND usage_status NOT IN ('CLOSED','CANCELLED')"),maintenanceOpen:one("SELECT COUNT(*) n FROM maintenance_work_order WHERE deleted_at IS NULL AND status NOT IN ('CLOSED','CANCELLED')"),documents:one('SELECT COUNT(*) n FROM asset_document WHERE deleted_at IS NULL AND active=1'),expiring:one("SELECT COUNT(*) n FROM asset_document WHERE deleted_at IS NULL AND active=1 AND expiry_date IS NOT NULL AND date(expiry_date)<=date('now','+60 day')")}; }

  listAssets(q=''){ const like=`%${q}%`; return this.db.prepare(`SELECT a.*,c.name company_name,s.name site_name,o.display_name owner_name,p.display_name responsible_name,(SELECT file_path FROM asset_photo ap WHERE ap.asset_id=a.id AND ap.deleted_at IS NULL ORDER BY ap.is_primary DESC,ap.created_at LIMIT 1) primary_photo FROM asset a LEFT JOIN company c ON c.id=a.company_id LEFT JOIN site s ON s.id=a.site_id LEFT JOIN owner_registry o ON o.id=a.owner_id LEFT JOIN person p ON p.id=a.responsible_person_id WHERE a.deleted_at IS NULL AND (a.asset_code LIKE ? OR a.name LIKE ? OR COALESCE(a.registration_no,'') LIKE ?) ORDER BY a.asset_code LIMIT 500`).all(like,like,like); }
  getAsset(id){ const asset=this.db.prepare(`SELECT a.*,c.name company_name,s.name site_name,o.display_name owner_name,p.display_name responsible_name FROM asset a LEFT JOIN company c ON c.id=a.company_id LEFT JOIN site s ON s.id=a.site_id LEFT JOIN owner_registry o ON o.id=a.owner_id LEFT JOIN person p ON p.id=a.responsible_person_id WHERE a.id=? AND a.deleted_at IS NULL`).get(id); if(!asset)return null; asset.documents=this.listDocuments({assetId:id}); asset.photos=this.db.prepare('SELECT * FROM asset_photo WHERE asset_id=? AND deleted_at IS NULL ORDER BY is_primary DESC,created_at DESC').all(id); asset.meters=this.db.prepare('SELECT * FROM meter_reading WHERE asset_id=? ORDER BY reading_at DESC LIMIT 30').all(id); asset.audit=this.listAudit('asset',id,50); return asset; }
  saveAsset(p){ const t=now(); if(p.id){const old=this.db.prepare('SELECT * FROM asset WHERE id=?').get(p.id);if(!old)throw new Error('Asset not found');this.db.prepare(`UPDATE asset SET asset_code=?,name=?,asset_kind=?,company_id=?,site_id=?,owner_id=?,responsible_person_id=?,registration_no=?,status=?,current_meter=?,current_meter_unit=?,updated_at=?,version_no=version_no+1 WHERE id=?`).run(p.asset_code,p.name,p.asset_kind,p.company_id||null,p.site_id||null,p.owner_id||null,p.responsible_person_id||null,p.registration_no||null,p.status||'AVAILABLE',Number(p.current_meter||0),p.current_meter_unit||'KM',t,p.id);this.audit('asset',p.id,'UPDATE',old,p);return{id:p.id}} const id=uid();this.db.prepare(`INSERT INTO asset(id,asset_code,name,asset_kind,company_id,site_id,owner_id,responsible_person_id,registration_no,status,current_meter,current_meter_unit,created_at,updated_at,version_no,sync_status) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,1,'LOCAL')`).run(id,p.asset_code,p.name,p.asset_kind,p.company_id||null,p.site_id||null,p.owner_id||null,p.responsible_person_id||null,p.registration_no||null,p.status||'AVAILABLE',Number(p.current_meter||0),p.current_meter_unit||'KM',t,t);this.audit('asset',id,'CREATE',null,p);return{id}; }
  deleteAsset(id){const used=this.db.prepare(`SELECT COUNT(*) n FROM usage_request WHERE deleted_at IS NULL AND (assigned_asset_id=? OR requested_asset_id=?)`).get(id,id).n;if(used)throw new Error('ทรัพย์สินมีประวัติการใช้งาน ไม่สามารถลบได้');const old=this.db.prepare('SELECT * FROM asset WHERE id=?').get(id);this.db.prepare('UPDATE asset SET deleted_at=?,status=? WHERE id=?').run(now(),'INACTIVE',id);this.audit('asset',id,'SOFT_DELETE',old,null);return{ok:true};}

  listDocuments({assetId=null,category='',status='',search=''}={}){const params=[];let where='d.deleted_at IS NULL';if(assetId){where+=' AND d.asset_id=?';params.push(assetId)}if(category){where+=' AND d.document_type=?';params.push(category)}if(search){where+=" AND (COALESCE(d.document_no,'') LIKE ? OR a.asset_code LIKE ? OR a.name LIKE ?)";const x=`%${search}%`;params.push(x,x,x)}if(status==='expired')where+=" AND d.expiry_date IS NOT NULL AND date(d.expiry_date)<date('now')";if(status==='60')where+=" AND d.expiry_date IS NOT NULL AND date(d.expiry_date)>=date('now') AND date(d.expiry_date)<=date('now','+60 day')";return this.db.prepare(`SELECT d.*,a.asset_code,a.name asset_name,dd.insurer_name,dd.policy_no,dd.premium,dd.coverage_start,dd.coverage_end,dd.tax_amount,CASE WHEN d.expiry_date IS NULL THEN NULL ELSE CAST(julianday(date(d.expiry_date))-julianday(date('now')) AS INTEGER) END remaining_days FROM asset_document d JOIN asset a ON a.id=d.asset_id LEFT JOIN document_detail dd ON dd.document_id=d.id WHERE ${where} ORDER BY COALESCE(d.expiry_date,'9999-12-31'),d.created_at DESC LIMIT 500`).all(...params);}
  saveDocument(p){const t=now();if(p.id){const old=this.db.prepare('SELECT * FROM asset_document WHERE id=?').get(p.id);if(!old)throw new Error('Document not found');this.db.prepare(`UPDATE asset_document SET document_type=?,document_no=?,issue_date=?,expiry_date=?,amount=?,file_path=COALESCE(?,file_path),active=?,updated_at=? WHERE id=?`).run(p.document_type,p.document_no||null,p.issue_date||null,p.expiry_date||null,Number(p.amount||0),p.file_path||null,p.active===false?0:1,t,p.id);this.saveDocumentDetail(p.id,p);this.audit('asset_document',p.id,'UPDATE',old,p);return{id:p.id}}const id=uid();this.db.prepare(`INSERT INTO asset_document(id,asset_id,document_type,document_no,issue_date,expiry_date,amount,file_path,version_no,active,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,1,1,?,?)`).run(id,p.asset_id,p.document_type,p.document_no||null,p.issue_date||null,p.expiry_date||null,Number(p.amount||0),p.file_path||null,t,t);this.saveDocumentDetail(id,p);this.audit('asset_document',id,'CREATE',null,p);return{id};}
  saveDocumentDetail(id,p){this.db.prepare(`INSERT INTO document_detail(document_id,insurer_name,policy_no,insurance_class,insured_amount,repair_condition,premium,coverage_start,coverage_end,renewal_date,tax_amount,metadata_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(document_id) DO UPDATE SET insurer_name=excluded.insurer_name,policy_no=excluded.policy_no,insurance_class=excluded.insurance_class,insured_amount=excluded.insured_amount,repair_condition=excluded.repair_condition,premium=excluded.premium,coverage_start=excluded.coverage_start,coverage_end=excluded.coverage_end,renewal_date=excluded.renewal_date,tax_amount=excluded.tax_amount,metadata_json=excluded.metadata_json`).run(id,p.insurer_name||null,p.policy_no||null,p.insurance_class||null,Number(p.insured_amount||0)||null,p.repair_condition||null,Number(p.premium||0)||null,p.coverage_start||null,p.coverage_end||null,p.renewal_date||null,Number(p.tax_amount||0)||null,p.metadata_json||null);}
  renewDocument(id,p){const old=this.db.prepare('SELECT * FROM asset_document WHERE id=?').get(id);if(!old)throw new Error('Document not found');const t=now(),nid=uid();this.db.prepare('UPDATE asset_document SET active=0,updated_at=? WHERE id=?').run(t,id);this.db.prepare(`INSERT INTO asset_document(id,asset_id,document_type,document_no,issue_date,expiry_date,amount,file_path,version_no,previous_version_id,active,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,1,?,?)`).run(nid,old.asset_id,p.document_type||old.document_type,p.document_no||old.document_no,p.issue_date||null,p.expiry_date||null,Number(p.amount||0),p.file_path||old.file_path,(old.version_no||1)+1,id,t,t);this.saveDocumentDetail(nid,p);this.audit('asset_document',nid,'RENEW',old,p);return{id:nid};}

  listPeople(q=''){const x=`%${q}%`;return this.db.prepare(`SELECT p.*,(SELECT GROUP_CONCAT(role_code,', ') FROM person_role r WHERE r.person_id=p.id AND r.active=1) roles,(SELECT COUNT(*) FROM user_account u WHERE u.person_id=p.id AND u.active=1) has_account FROM person p WHERE p.active=1 AND (p.display_name LIKE ? OR COALESCE(p.employee_id,'') LIKE ?) ORDER BY p.display_name`).all(x,x)}
  savePerson(p){const t=now();if(p.id){const old=this.db.prepare('SELECT * FROM person WHERE id=?').get(p.id);this.db.prepare(`UPDATE person SET person_code=?,employee_id=?,hr_employee_ref=?,display_name=?,company_id=?,department_name=?,position_name=?,work_email=?,phone=?,employment_status=?,source_system=?,updated_at=? WHERE id=?`).run(p.person_code||null,p.employee_id||null,p.hr_employee_ref||null,p.display_name,p.company_id||null,p.department_name||null,p.position_name||null,p.work_email||null,p.phone||null,p.employment_status||'ACTIVE',p.source_system||'LOCAL',t,p.id);this.setPersonRoles(p.id,p.roles||[]);this.audit('person',p.id,'UPDATE',old,p);return{id:p.id}}const id=uid();this.db.prepare(`INSERT INTO person(id,person_code,employee_id,hr_employee_ref,display_name,company_id,department_name,position_name,work_email,phone,employment_status,source_system,active,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,1,?,?)`).run(id,p.person_code||null,p.employee_id||null,p.hr_employee_ref||null,p.display_name,p.company_id||null,p.department_name||null,p.position_name||null,p.work_email||null,p.phone||null,p.employment_status||'ACTIVE',p.source_system||'LOCAL',t,t);this.setPersonRoles(id,p.roles||[]);this.audit('person',id,'CREATE',null,p);return{id};}
  setPersonRoles(personId,roles){this.db.prepare('UPDATE person_role SET active=0 WHERE person_id=?').run(personId);for(const role of roles){this.db.prepare(`INSERT INTO person_role(id,person_id,role_code,active) VALUES(?,?,?,1) ON CONFLICT(person_id,role_code) DO UPDATE SET active=1`).run(uid(),personId,role)}}
  listUsers(){return this.db.prepare(`SELECT u.*,p.display_name,p.employee_id FROM user_account u JOIN person p ON p.id=u.person_id ORDER BY p.display_name`).all()}
  saveUser(p){if(p.id){this.db.prepare('UPDATE user_account SET person_id=?,login_email=?,system_role=?,data_scope=?,auth_provider=?,active=? WHERE id=?').run(p.person_id,p.login_email||null,p.system_role||'USER',p.data_scope||'SITE',p.auth_provider||'LOCAL',p.active===false?0:1,p.id);return{id:p.id}}const id=uid();this.db.prepare('INSERT INTO user_account(id,person_id,login_email,system_role,data_scope,auth_provider,active) VALUES(?,?,?,?,?,?,1)').run(id,p.person_id,p.login_email||null,p.system_role||'USER',p.data_scope||'SITE',p.auth_provider||'LOCAL');return{id};}

  listCompanies(){return this.db.prepare('SELECT * FROM company ORDER BY active DESC,name').all()}
  saveCompany(p){const t=now();if(p.id){this.db.prepare('UPDATE company SET code=?,name=?,active=?,updated_at=? WHERE id=?').run(p.code,p.name,p.active===false?0:1,t,p.id);return{id:p.id}}const id=uid();this.db.prepare('INSERT INTO company(id,code,name,active,created_at,updated_at) VALUES(?,?,?,1,?,?)').run(id,p.code,p.name,t,t);return{id};}
  listSites(){return this.db.prepare('SELECT s.*,c.name company_name FROM site s LEFT JOIN company c ON c.id=s.company_id ORDER BY s.active DESC,s.name').all()}
  saveSite(p){if(p.id){this.db.prepare('UPDATE site SET code=?,name=?,company_id=?,active=? WHERE id=?').run(p.code,p.name,p.company_id||null,p.active===false?0:1,p.id);return{id:p.id}}const id=uid();this.db.prepare('INSERT INTO site(id,code,name,company_id,active) VALUES(?,?,?,?,1)').run(id,p.code,p.name,p.company_id||null);return{id};}
  listOwners(){return this.db.prepare('SELECT * FROM owner_registry ORDER BY active DESC,display_name').all()}
  saveOwner(p){if(p.id){this.db.prepare(`UPDATE owner_registry SET owner_code=?,owner_type=?,reference_type=?,reference_id=?,display_name=?,usage_classification=?,fuel_reimbursement_eligible=?,repair_reimbursement_eligible=?,authorization_start=?,authorization_end=?,note=?,active=? WHERE id=?`).run(p.owner_code,p.owner_type,p.reference_type||null,p.reference_id||null,p.display_name,p.usage_classification||'UNVERIFIED',p.fuel_reimbursement_eligible?1:0,p.repair_reimbursement_eligible?1:0,p.authorization_start||null,p.authorization_end||null,p.note||null,p.active===false?0:1,p.id);return{id:p.id}}const id=uid();this.db.prepare(`INSERT INTO owner_registry(id,owner_code,owner_type,reference_type,reference_id,display_name,usage_classification,fuel_reimbursement_eligible,repair_reimbursement_eligible,authorization_start,authorization_end,note,active) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,1)`).run(id,p.owner_code,p.owner_type,p.reference_type||null,p.reference_id||null,p.display_name,p.usage_classification||'UNVERIFIED',p.fuel_reimbursement_eligible?1:0,p.repair_reimbursement_eligible?1:0,p.authorization_start||null,p.authorization_end||null,p.note||null);return{id};}
  listMasters(type=''){return type?this.db.prepare('SELECT * FROM master_item WHERE master_type=? ORDER BY active DESC,name').all(type):this.db.prepare('SELECT * FROM master_item ORDER BY master_type,name').all()}
  saveMaster(p){const t=now();if(p.id){this.db.prepare('UPDATE master_item SET master_type=?,code=?,name=?,parent_id=?,metadata_json=?,active=?,updated_at=? WHERE id=?').run(p.master_type,p.code,p.name,p.parent_id||null,p.metadata_json||null,p.active===false?0:1,t,p.id);return{id:p.id}}const id=uid();this.db.prepare('INSERT INTO master_item(id,master_type,code,name,parent_id,metadata_json,active,created_at,updated_at) VALUES(?,?,?,?,?,?,1,?,?)').run(id,p.master_type,p.code,p.name,p.parent_id||null,p.metadata_json||null,t,t);return{id};}
  listAudit(entityType=null,entityId=null,limit=200){let w='1=1',p=[];if(entityType){w+=' AND entity_type=?';p.push(entityType)}if(entityId){w+=' AND entity_id=?';p.push(entityId)}p.push(limit);return this.db.prepare(`SELECT * FROM audit_log WHERE ${w} ORDER BY created_at DESC LIMIT ?`).all(...p)}

  listUsageRequests(){return this.db.prepare(`SELECT u.*,a.asset_code assigned_asset_code,a.name assigned_asset_name FROM usage_request u LEFT JOIN asset a ON a.id=u.assigned_asset_id WHERE u.deleted_at IS NULL ORDER BY u.created_at DESC LIMIT 500`).all()}
  getUsage(id){return this.db.prepare(`SELECT u.*,a.asset_code assigned_asset_code,a.name assigned_asset_name,a.registration_no FROM usage_request u LEFT JOIN asset a ON a.id=u.assigned_asset_id WHERE u.id=?`).get(id)}
  checkAssetConflict(assetId,start,end,excludeId=null){if(!assetId)return false;return this.db.prepare(`SELECT COUNT(*) n FROM usage_request WHERE deleted_at IS NULL AND assigned_asset_id=? AND usage_status NOT IN ('CLOSED','CANCELLED') AND id<>COALESCE(?, '') AND planned_start_at < ? AND planned_end_at > ?`).get(assetId,excludeId,end,start).n>0}
  createUsageRequest(p){const conflict=this.checkAssetConflict(p.assigned_asset_id,p.planned_start_at,p.planned_end_at);const id=uid(),t=now();this.db.prepare(`INSERT INTO usage_request(id,request_no,requester_name,department_name,purpose,destination,planned_start_at,planned_end_at,requested_asset_id,assigned_asset_id,approval_status,usage_status,meter_before,meter_unit,fuel_before,created_at,updated_at,version_no,sync_status) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,p.request_no||`REQ-${Date.now()}`,p.requester_name,p.department_name||null,p.purpose,p.destination||null,p.planned_start_at,p.planned_end_at,p.requested_asset_id||null,p.assigned_asset_id||null,'PENDING_DOCUMENT','DRAFT',p.meter_before?Number(p.meter_before):null,p.meter_unit||'KM',p.fuel_before||null,t,t,1,'LOCAL');this.audit('usage_request',id,'CREATE',null,p);return{id,conflict};}
  updateUsageStatus(p){const old=this.getUsage(p.id);if(!old)throw new Error('Usage request not found');const t=now();this.db.prepare(`UPDATE usage_request SET approval_status=COALESCE(?,approval_status),usage_status=COALESCE(?,usage_status),approved_by_name=COALESCE(?,approved_by_name),approved_at=COALESCE(?,approved_at),approval_document_ref=COALESCE(?,approval_document_ref),meter_before=COALESCE(?,meter_before),fuel_before=COALESCE(?,fuel_before),assigned_asset_id=COALESCE(?,assigned_asset_id),checked_out_at=COALESCE(?,checked_out_at),updated_at=?,version_no=version_no+1 WHERE id=?`).run(p.approval_status||null,p.usage_status||null,p.approved_by_name||null,p.approved_at||null,p.approval_document_ref||null,p.meter_before!==''&&p.meter_before!=null?Number(p.meter_before):null,p.fuel_before||null,p.assigned_asset_id||null,p.checked_out_at||null,t,p.id);this.audit('usage_request',p.id,'STATUS_UPDATE',old,p);return{ok:true};}
  recordReturn(p){const old=this.getUsage(p.id);if(!old)throw new Error('Usage request not found');const t=now(),meter=Number(p.meter_after);if(Number.isNaN(meter))throw new Error('กรุณาระบุเลขไมล์/ชั่วโมงหลังใช้');if(old.meter_before!=null&&meter<Number(old.meter_before))throw new Error('เลขไมล์/ชั่วโมงหลังใช้ต้องไม่น้อยกว่าก่อนใช้');this.db.prepare(`UPDATE usage_request SET returned_at=?,meter_after=?,fuel_after=?,condition_after=?,incident_flag=?,return_note=?,returned_by_name=?,received_by_name=?,usage_status='CLOSED',updated_at=?,version_no=version_no+1 WHERE id=?`).run(p.returned_at||t,meter,p.fuel_after||null,p.condition_after||null,p.incident_flag?1:0,p.return_note||null,p.returned_by_name||null,p.received_by_name||null,t,p.id);if(old.assigned_asset_id){this.db.prepare('UPDATE asset SET current_meter=?,status=?,updated_at=?,version_no=version_no+1 WHERE id=?').run(meter,'AVAILABLE',t,old.assigned_asset_id);this.db.prepare('INSERT INTO meter_reading(id,asset_id,reading_value,unit,reading_at,source_type,source_id,created_at) VALUES(?,?,?,?,?,?,?,?)').run(uid(),old.assigned_asset_id,meter,old.meter_unit||'KM',p.returned_at||t,'USAGE_RETURN',p.id,t)}this.audit('usage_request',p.id,'RETURN',old,p);return{ok:true};}

  async backup(target){await this.db.backup(target)}
  restore(source){this.db.close();fs.copyFileSync(source,this.file);this.open();this.migrate();return{ok:true}}
}
module.exports={DatabaseService};
