const Database = require('better-sqlite3');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const uid = () => crypto.randomUUID();

class DatabaseService {
  constructor(file, migrationsDir) { this.file=file; this.migrationsDir=migrationsDir; this.open(); }
  open(){ this.db=new Database(this.file); this.db.pragma('foreign_keys = ON'); this.db.pragma('journal_mode = WAL'); }
  migrate() {
    this.db.exec('CREATE TABLE IF NOT EXISTS schema_migrations (version TEXT PRIMARY KEY, applied_at TEXT NOT NULL)');
    const done = new Set(this.db.prepare('SELECT version FROM schema_migrations').all().map(x=>x.version));
    for (const file of fs.readdirSync(this.migrationsDir).filter(x=>x.endsWith('.sql')).sort()) {
      if (done.has(file)) continue;
      const sql=fs.readFileSync(path.join(this.migrationsDir,file),'utf8');
      const tx=this.db.transaction(()=>{ this.db.exec(sql); this.db.prepare('INSERT INTO schema_migrations(version,applied_at) VALUES (?,?)').run(file,new Date().toISOString()); }); tx();
    }
  }
  dashboardSummary(){
    const one=(sql)=>this.db.prepare(sql).get().n;
    return { assets:one('SELECT COUNT(*) n FROM asset WHERE deleted_at IS NULL'), available:one("SELECT COUNT(*) n FROM asset WHERE deleted_at IS NULL AND status='AVAILABLE'"), usageOpen:one("SELECT COUNT(*) n FROM usage_request WHERE deleted_at IS NULL AND usage_status NOT IN ('CLOSED','CANCELLED')"), maintenanceOpen:one("SELECT COUNT(*) n FROM maintenance_work_order WHERE deleted_at IS NULL AND status NOT IN ('CLOSED','CANCELLED')") };
  }
  listAssets(q=''){ return this.db.prepare(`SELECT a.*, c.name company_name, s.name site_name, o.display_name owner_name, p.display_name responsible_name FROM asset a LEFT JOIN company c ON c.id=a.company_id LEFT JOIN site s ON s.id=a.site_id LEFT JOIN owner_registry o ON o.id=a.owner_id LEFT JOIN person p ON p.id=a.responsible_person_id WHERE a.deleted_at IS NULL AND (a.asset_code LIKE ? OR a.name LIKE ? OR IFNULL(a.registration_no,'') LIKE ?) ORDER BY a.asset_code LIMIT 500`).all(...Array(3).fill(`%${q}%`)); }
  getAsset(id){ return this.db.prepare(`SELECT a.*, c.name company_name, s.name site_name, o.display_name owner_name, p.display_name responsible_name FROM asset a LEFT JOIN company c ON c.id=a.company_id LEFT JOIN site s ON s.id=a.site_id LEFT JOIN owner_registry o ON o.id=a.owner_id LEFT JOIN person p ON p.id=a.responsible_person_id WHERE a.id=?`).get(id); }
  saveAsset(p){
    const now=new Date().toISOString();
    if(p.id){ const old=this.getAsset(p.id); this.db.prepare(`UPDATE asset SET asset_code=?,name=?,asset_kind=?,company_id=?,site_id=?,owner_id=?,responsible_person_id=?,registration_no=?,status=?,current_meter=?,current_meter_unit=?,updated_at=?,version_no=version_no+1 WHERE id=?`).run(p.asset_code,p.name,p.asset_kind,p.company_id||null,p.site_id||null,p.owner_id||null,p.responsible_person_id||null,p.registration_no||null,p.status||'AVAILABLE',Number(p.current_meter||0),p.current_meter_unit||'KM',now,p.id); this.audit('asset',p.id,'UPDATE',old,p); return {id:p.id}; }
    const id=uid(); this.db.prepare(`INSERT INTO asset(id,asset_code,name,asset_kind,company_id,site_id,owner_id,responsible_person_id,registration_no,status,current_meter,current_meter_unit,created_at,updated_at,version_no,sync_status) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,1,'LOCAL')`).run(id,p.asset_code,p.name,p.asset_kind,p.company_id||null,p.site_id||null,p.owner_id||null,p.responsible_person_id||null,p.registration_no||null,p.status||'AVAILABLE',Number(p.current_meter||0),p.current_meter_unit||'KM',now,now); this.audit('asset',id,'CREATE',null,p); return {id};
  }
  deleteAsset(id){ const used=this.db.prepare(`SELECT COUNT(*) n FROM usage_request WHERE deleted_at IS NULL AND (assigned_asset_id=? OR requested_asset_id=?)`).get(id,id).n; if(used) throw new Error('ทรัพย์สินมีประวัติการใช้งาน ไม่สามารถลบได้'); const now=new Date().toISOString(); this.db.prepare('UPDATE asset SET deleted_at=?,status=? WHERE id=?').run(now,'INACTIVE',id); this.audit('asset',id,'SOFT_DELETE',null,null); return {ok:true}; }

  listPeople(){ return this.db.prepare(`SELECT * FROM person WHERE active=1 ORDER BY display_name`).all(); }
  savePerson(p){ const now=new Date().toISOString(); if(p.id){ this.db.prepare(`UPDATE person SET person_code=?,employee_id=?,display_name=?,department_name=?,position_name=?,work_email=?,phone=?,employment_status=?,updated_at=? WHERE id=?`).run(p.person_code||null,p.employee_id||null,p.display_name,p.department_name||null,p.position_name||null,p.work_email||null,p.phone||null,p.employment_status||'ACTIVE',now,p.id); return {id:p.id}; } const id=uid(); this.db.prepare(`INSERT INTO person(id,person_code,employee_id,display_name,department_name,position_name,work_email,phone,employment_status,source_system,active,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,'LOCAL',1,?,?)`).run(id,p.person_code||null,p.employee_id||null,p.display_name,p.department_name||null,p.position_name||null,p.work_email||null,p.phone||null,p.employment_status||'ACTIVE',now,now); return {id}; }
  listCompanies(){ return this.db.prepare('SELECT * FROM company WHERE active=1 ORDER BY name').all(); }
  saveCompany(p){ const now=new Date().toISOString(); if(p.id){this.db.prepare('UPDATE company SET code=?,name=?,updated_at=? WHERE id=?').run(p.code,p.name,now,p.id);return {id:p.id};} const id=uid();this.db.prepare('INSERT INTO company(id,code,name,active,created_at,updated_at) VALUES(?,?,?,1,?,?)').run(id,p.code,p.name,now,now);return {id}; }
  listSites(){ return this.db.prepare(`SELECT s.*,c.name company_name FROM site s LEFT JOIN company c ON c.id=s.company_id WHERE s.active=1 ORDER BY s.name`).all(); }
  saveSite(p){ if(p.id){this.db.prepare('UPDATE site SET code=?,name=?,company_id=? WHERE id=?').run(p.code,p.name,p.company_id||null,p.id);return {id:p.id};} const id=uid();this.db.prepare('INSERT INTO site(id,code,name,company_id,active) VALUES(?,?,?,?,1)').run(id,p.code,p.name,p.company_id||null);return {id}; }
  listOwners(){ return this.db.prepare('SELECT * FROM owner_registry WHERE active=1 ORDER BY display_name').all(); }
  saveOwner(p){ if(p.id){this.db.prepare('UPDATE owner_registry SET owner_code=?,owner_type=?,display_name=?,usage_classification=?,fuel_reimbursement_eligible=?,repair_reimbursement_eligible=?,note=? WHERE id=?').run(p.owner_code||null,p.owner_type,p.display_name,p.usage_classification||'UNVERIFIED',p.fuel_reimbursement_eligible?1:0,p.repair_reimbursement_eligible?1:0,p.note||null,p.id);return {id:p.id};} const id=uid();this.db.prepare(`INSERT INTO owner_registry(id,owner_code,owner_type,display_name,usage_classification,fuel_reimbursement_eligible,repair_reimbursement_eligible,note,active) VALUES(?,?,?,?,?,?,?,?,1)`).run(id,p.owner_code||null,p.owner_type,p.display_name,p.usage_classification||'UNVERIFIED',p.fuel_reimbursement_eligible?1:0,p.repair_reimbursement_eligible?1:0,p.note||null);return {id}; }

  listUsageRequests(){ return this.db.prepare(`SELECT u.*, a.asset_code assigned_asset_code, a.name assigned_asset_name FROM usage_request u LEFT JOIN asset a ON a.id=u.assigned_asset_id WHERE u.deleted_at IS NULL ORDER BY u.created_at DESC LIMIT 500`).all(); }
  getUsage(id){ return this.db.prepare(`SELECT u.*, a.asset_code assigned_asset_code,a.name assigned_asset_name,a.registration_no FROM usage_request u LEFT JOIN asset a ON a.id=u.assigned_asset_id WHERE u.id=?`).get(id); }
  createUsageRequest(p){ const id=uid(), now=new Date().toISOString(); this.db.prepare(`INSERT INTO usage_request(id,request_no,requester_name,department_name,purpose,destination,planned_start_at,planned_end_at,requested_asset_id,assigned_asset_id,approval_status,usage_status,meter_before,meter_unit,fuel_before,created_at,updated_at,version_no,sync_status) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,p.request_no||`REQ-${Date.now()}`,p.requester_name,p.department_name||null,p.purpose,p.destination||null,p.planned_start_at,p.planned_end_at,p.requested_asset_id||null,p.assigned_asset_id||null,'PENDING_DOCUMENT','DRAFT',p.meter_before?Number(p.meter_before):null,p.meter_unit||'KM',p.fuel_before||null,now,now,1,'LOCAL'); this.audit('usage_request',id,'CREATE',null,p); return {id}; }
  updateUsageStatus(p){ const old=this.getUsage(p.id); if(!old) throw new Error('Usage request not found'); const now=new Date().toISOString(); this.db.prepare(`UPDATE usage_request SET approval_status=COALESCE(?,approval_status), usage_status=COALESCE(?,usage_status), approved_by_name=COALESCE(?,approved_by_name), approved_at=COALESCE(?,approved_at), approval_document_ref=COALESCE(?,approval_document_ref), meter_before=COALESCE(?,meter_before), fuel_before=COALESCE(?,fuel_before), assigned_asset_id=COALESCE(?,assigned_asset_id), checked_out_at=COALESCE(?,checked_out_at), updated_at=?, version_no=version_no+1 WHERE id=?`).run(p.approval_status||null,p.usage_status||null,p.approved_by_name||null,p.approved_at||null,p.approval_document_ref||null,p.meter_before!==''&&p.meter_before!=null?Number(p.meter_before):null,p.fuel_before||null,p.assigned_asset_id||null,p.checked_out_at||null,now,p.id); this.audit('usage_request',p.id,'STATUS_UPDATE',old,p); return {ok:true}; }
  recordReturn(p){ const old=this.getUsage(p.id); if(!old) throw new Error('Usage request not found'); const now=new Date().toISOString(); const meter=Number(p.meter_after); if(Number.isNaN(meter)) throw new Error('กรุณาระบุเลขไมล์/ชั่วโมงหลังใช้'); if(old.meter_before!=null && meter<Number(old.meter_before)) throw new Error('เลขไมล์/ชั่วโมงหลังใช้ต้องไม่น้อยกว่าก่อนใช้'); this.db.prepare(`UPDATE usage_request SET returned_at=?, meter_after=?, fuel_after=?, condition_after=?, incident_flag=?, return_note=?, returned_by_name=?, received_by_name=?, usage_status='CLOSED', updated_at=?, version_no=version_no+1 WHERE id=?`).run(p.returned_at||now,meter,p.fuel_after||null,p.condition_after||null,p.incident_flag?1:0,p.return_note||null,p.returned_by_name||null,p.received_by_name||null,now,p.id); if(old.assigned_asset_id){ this.db.prepare('UPDATE asset SET current_meter=?,status=?,updated_at=?,version_no=version_no+1 WHERE id=?').run(meter,'AVAILABLE',now,old.assigned_asset_id); this.db.prepare('INSERT INTO meter_reading(id,asset_id,reading_value,unit,reading_at,source_type,source_id,created_at) VALUES(?,?,?,?,?,?,?,?)').run(uid(),old.assigned_asset_id,meter,old.meter_unit||'KM',p.returned_at||now,'USAGE_RETURN',p.id,now); } this.audit('usage_request',p.id,'RETURN',old,p); return {ok:true}; }
  checkAssetConflict(assetId,start,end,excludeId=null){ return this.db.prepare(`SELECT COUNT(*) n FROM usage_request WHERE deleted_at IS NULL AND assigned_asset_id=? AND usage_status NOT IN ('CLOSED','CANCELLED') AND id<>COALESCE(?, '') AND planned_start_at < ? AND planned_end_at > ?`).get(assetId,excludeId,end,start).n>0; }

  audit(entity,id,action,before,after){ this.db.prepare('INSERT INTO audit_log(id,entity_type,entity_id,action,before_json,after_json,created_at) VALUES(?,?,?,?,?,?,?)').run(uid(),entity,id,action,before?JSON.stringify(before):null,after?JSON.stringify(after):null,new Date().toISOString()); }
  async backup(target){ await this.db.backup(target); }
  restore(source){ this.db.close(); fs.copyFileSync(source,this.file); this.open(); this.migrate(); return {ok:true}; }
}
module.exports={DatabaseService};
