const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm');

function load(role='admin',{view='dashboard'}={}){
  const STATE={vendors:[{id:'V1',code:'VEN-001',name:'อู่ เอ',type:'external'},{id:'V2',code:'VEN-002',name:'อู่ลบแล้ว',type:'external',deleted:true},{id:'V3',code:'VEN-003',name:'อู่พักใช้',type:'external',active:false},{id:'V4',code:'VEN-004',name:'หน่วยซ่อมกลาง',type:'internal'}],assets:[{id:'A1',plate:'กข 1234',deleted:false,status:'available'}],maintenance:[],expenses:[]};
  const NAV=[['ตั้งค่า',[['masters','ตั้งค่าข้อมูลทรัพย์สิน']]]];const PARITY_MENU={admin:[],manager:[],fleetOfficer:[],clerk:[],requester:[],viewer:[]};
  const calls={render:0,toast:[],audit:[],form:0,save:[]};const elements=new Map();const el=id=>{if(!elements.has(id))elements.set(id,{value:'',innerHTML:'',oninput:null,onchange:null,onclick:null});return elements.get(id)};
  const mkSel=(label,name,opts,value='')=>`<label>${label}<select name="${name}">${opts.map(o=>`<option value="${o[0]}"${String(o[0])===String(value)?' selected':''}>${o[1]}</option>`).join('')}</select></label>`;
  const ctx={STATE,NAV,PARITY_MENU,CURRENT_ROLE:role,window:null,console,structuredClone:global.structuredClone,render:()=>{calls.render++},view,assetDetailId:'',migrateState:()=>{},setTimeout:fn=>{fn();return 0},save:(...a)=>calls.save.push(a),pAudit:(...a)=>calls.audit.push(a),renderNav:()=>{},parityRefreshShell:()=>{},setHead:()=>{},content:{innerHTML:''},toast:m=>calls.toast.push(m),confirm:()=>true,now:()=> '2026-09-09T00:00:00.000Z',today:()=> '2026-09-09',uid:p=>`${p}-TEST`,esc:v=>String(v??''),pill:v=>String(v),$:s=>el(s),$$:()=>[],fld:(l,n)=>`<input name="${n}">`,sel:mkSel,selObj:(l,n)=>`<select name="${n}"></select>`,area:(l,n)=>`<textarea name="${n}"></textarea>`,formModal:(title,html,onSave)=>{calls.form++;ctx.__form={title,html,onSave}},maintenanceForm:function legacyMaintenanceForm(){}};
  ctx.window=ctx;vm.createContext(ctx);vm.runInContext(fs.readFileSync('src/renderer/app/maintenance-v1-vendor-foundation.js','utf8'),ctx);return {ctx,STATE,NAV,PARITY_MENU,api:ctx.FLEET_VENDOR_TEST,calls};
}

test('vendor foundation initializes additive state without touching existing vendor data',()=>{const {STATE,api}=load();api.ensureVendorState();assert.equal(STATE.vendors.length,4);assert.equal(STATE.vendors[0].active,true);assert.equal(STATE.vendors[0].deleted,false);assert.equal(STATE.vendors[0].source,'manual');assert.equal(STATE.vendors[1].deleted,true)});
test('vendor duplicate detection normalizes name and ignores soft-deleted rows',()=>{const {api}=load();assert.equal(api.vendorDuplicate('  อู่ เอ  '),true);assert.equal(api.vendorDuplicate('อู่ลบแล้ว'),false);assert.equal(api.vendorDuplicate('อู่ เอ','V1'),false)});
test('vendor duplicate code protection normalizes code, ignores deleted rows and excludes self',()=>{const {api}=load();assert.equal(api.vendorCodeDuplicate(' ven-001 '),true);assert.equal(api.vendorCodeDuplicate('VEN-002'),false);assert.equal(api.vendorCodeDuplicate('VEN-001','V1'),false)});
test('vendor code generator skips existing codes',()=>{const {api}=load();assert.equal(api.nextVendorCode(),'VEN-005')});
test('vendor permissions fail closed and follow locked role intent',()=>{for(const [r,m,d] of [['admin',true,true],['manager',true,false],['fleetOfficer',true,false],['clerk',false,false],['requester',false,false],['viewer',false,false]]){const {api}=load(r);assert.equal(api.canManageVendor(),m,r);assert.equal(api.canDeleteVendor(),d,r)}});
test('vendor page is registered additively and only authorized roles receive menu access',()=>{const {NAV,PARITY_MENU}=load();assert.ok(NAV.find(x=>x[0]==='ตั้งค่า')[1].some(x=>x[0]==='vendors'));for(const role of ['admin','manager','fleetOfficer'])assert.ok(PARITY_MENU[role].includes('vendors'));for(const role of ['clerk','requester','viewer'])assert.ok(!PARITY_MENU[role].includes('vendors'))});
test('wrapped render delegates existing views to original render',()=>{for(const view of ['dashboard','assets','documents']){const {ctx,calls}=load('admin',{view});ctx.render();assert.equal(calls.render,1,view)}});
test('wrapped render handles vendor view without delegating to original render',()=>{const {ctx,calls}=load('admin',{view:'vendors'});ctx.render();assert.equal(calls.render,0)});
test('deleteVendor enforces permission at function level',()=>{for(const role of ['manager','fleetOfficer','viewer']){const {api,STATE,calls}=load(role);api.deleteVendor('V1');assert.notEqual(STATE.vendors[0].deleted,true,role);assert.ok(calls.toast.some(x=>x.includes('เฉพาะ Admin')),role)}});
test('vendorForm blocks unauthorized roles before opening form',()=>{for(const role of ['clerk','requester','viewer']){const {api,calls}=load(role);api.vendorForm();assert.equal(calls.form,0,role);assert.ok(calls.toast.length,role)}});
test('vendor form duplicate code blocks new record but permits own code on edit',async()=>{const a=load('admin');a.api.vendorForm();await assert.rejects(async()=>a.ctx.__form.onSave({code:'VEN-001',name:'อู่ใหม่',type:'external',active:'true'}),/รหัสผู้ให้บริการซ้ำ/);const b=load('admin');b.api.vendorForm('V1');assert.doesNotThrow(()=>b.ctx.__form.onSave({code:'VEN-001',name:'อู่ เอ',type:'external',active:'true'}))});
test('vendor audit uses current baseline pAudit path with actual role context available',()=>{const {api,ctx,calls}=load('manager');api.vendorForm();ctx.__form.onSave({code:'VEN-005',name:'อู่ใหม่',type:'external',active:'true'});assert.equal(calls.audit.length,1);assert.equal(calls.audit[0][0],'เพิ่มผู้ให้บริการ');assert.equal(calls.audit[0][1],'vendor')});
test('soft-deleted vendor remains historically resolvable but is not editable',()=>{const {api,ctx}=load('admin');api.vendorDetail('V2');assert.match(ctx.content.innerHTML,/ข้อมูลประวัติ/);assert.doesNotMatch(ctx.content.innerHTML,/id="vendorEdit"/);assert.equal(api.vendorNameById('V2'),'อู่ลบแล้ว')});
test('legacy maintenance vendor selector contains only active non-deleted Vendor Master rows',()=>{const {api}=load();const html=api.vendorSelectHtml();assert.match(html,/V1/);assert.match(html,/อู่ เอ/);assert.match(html,/V4/);assert.match(html,/หน่วยซ่อมกลาง/);assert.doesNotMatch(html,/V2/);assert.doesNotMatch(html,/อู่ลบแล้ว/);assert.doesNotMatch(html,/V3/);assert.doesNotMatch(html,/อู่พักใช้/)});
test('maintenance form is overridden additively and uses vendorId instead of free-text vendor',()=>{const {ctx}=load();ctx.maintenanceForm();assert.match(ctx.__form.html,/name="vendorId"/);assert.doesNotMatch(ctx.__form.html,/name="vendor"/)});
test('saving legacy Work Order stores vendorId and immutable name snapshot while preserving compatibility vendor',()=>{const {api,STATE}=load();const x=api.saveLegacyMaintenanceWithVendor({assetId:'A1',maintenanceType:'repair',issue:'เปลี่ยนลูกปืน',meterValue:'1000',vendorId:'V1',cost:'1250.50',status:'repairing'});assert.equal(x.vendorId,'V1');assert.equal(x.vendorNameSnapshot,'อู่ เอ');assert.equal(x.vendor,'อู่ เอ');assert.equal(x.cost,1250.5);assert.equal(STATE.maintenance.length,1);assert.equal(STATE.expenses[0].sourceId,x.id);assert.equal(STATE.assets[0].status,'repair')});
test('crafted save cannot use inactive or soft-deleted vendor IDs',()=>{for(const id of ['V2','V3']){const {api}=load();assert.throws(()=>api.saveLegacyMaintenanceWithVendor({assetId:'A1',vendorId:id,cost:'0',status:'new'}),/ไม่พร้อมใช้งาน/)}});
test('legacy Work Order may omit vendor without fabricating an internal vendor',()=>{const {api}=load();const x=api.saveLegacyMaintenanceWithVendor({assetId:'A1',vendorId:'',cost:'0',status:'new'});assert.equal(x.vendorId,'');assert.equal(x.vendorNameSnapshot,'');assert.equal(x.vendor,'')});
test('historical snapshot wins after Vendor Master rename or soft delete',()=>{const {api,STATE}=load();const x=api.saveLegacyMaintenanceWithVendor({assetId:'A1',vendorId:'V1',cost:'0',status:'closed'});STATE.vendors[0].name='ชื่อใหม่';STATE.vendors[0].deleted=true;assert.equal(api.vendorNameById(x.vendorId,x.vendorNameSnapshot),'อู่ เอ')});
test('vendor implementation remains isolated from locked asset/document functions',()=>{const src=fs.readFileSync('src/renderer/app/maintenance-v1-vendor-foundation.js','utf8');assert.match(src,/v\.deleted=true/);assert.match(src,/pAudit/);assert.doesNotMatch(src,/assetProfile\s*=|documentPage\s*=|renderDocTable\s*=|assetForm/);const index=fs.readFileSync('index.html','utf8');assert.match(index,/maintenance-v1-vendor-foundation\.js/)});
