const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('fs');
const vm=require('vm');
function load(role='admin',ok=true){
 const audits=[];let n=0;
 const STATE={workOrders:[],repairItems:[],maintenanceRequests:[{id:'R1',requestNo:'MR-1',assetId:'A1',maintenanceType:'repair',meterValue:10,proposedVendorId:'V1',proposedVendorNameSnapshot:'Vendor',issue:'Brake'}],assets:[{id:'A1',plate:'ABC'}],audit:[],userAccounts:[{role:'admin',personId:'PA',active:true},{role:'manager',personId:'PM',active:true},{role:'fleetOfficer',personId:'PF',active:true}]};
 const content={innerHTML:'',querySelector(s){return s==='#apdPanels'&&this.innerHTML.includes('apdPanels')?{}:s==='#woCreatePanel'&&this.innerHTML.includes('woCreatePanel')?{}:null},insertAdjacentHTML(_,h){this.innerHTML+=h}};
 const req={requestDetail(id){content.innerHTML=`<div id="apdPanels">${id}</div>`}};
 const ctx={STATE,CURRENT_ROLE:role,window:null,content,console,structuredClone,uid:p=>`${p}-${++n}`,now:()=>`2026-09-11T00:00:0${n}Z`,esc:v=>String(v??''),pAudit:(action,entity,id,before,after)=>audits.push({action,entity,id,before,after}),MutationObserver:function(){this.observe=()=>{}},setHead:()=>{},toast:()=>{},formModal:()=>{},setTimeout:f=>f(),$:()=>null,$$:()=>[],prompt:()=>''};
 ctx.window=ctx;ctx.FLEET_MAINTENANCE_REQUEST_TEST=req;ctx.FLEET_MAINTENANCE_APPROVAL_DOCUMENT_API={hasApprovedResult:id=>id==='R1'&&ok,resultForRequest:()=>({externalApprovedAmount:500}),docsForRequest:()=>[]};
 vm.createContext(ctx);vm.runInContext(fs.readFileSync('src/renderer/app/maintenance-v1-workorder.js','utf8'),ctx);
 return {ctx,STATE,api:ctx.FLEET_MAINTENANCE_WORKORDER_TEST,prod:ctx.FLEET_MAINTENANCE_WORKORDER_API,audits,content,req,role:r=>ctx.CURRENT_ROLE=r,approve:v=>ok=v};
}
test('approval guard and inherit',()=>{const x=load('admin',false);assert.throws(()=>x.api.createFromRequest('R1'));x.approve(true);const w=x.api.createFromRequest('R1');assert.equal(w.sourceRequestId,'R1');assert.equal(w.assetId,'A1');assert.equal(w.repairMode,'internal');assert.equal(w.approvedAmount,500);assert.equal(x.api.itemsFor(w.id)[0].description,'Brake')});
test('one request creates many work orders',()=>{const x=load();const a=x.api.createFromRequest('R1'),b=x.api.createFromRequest('R1');assert.notEqual(a.id,b.id);assert.equal(a.sourceRequestId,b.sourceRequestId);assert.equal(Object.hasOwn(x.STATE.maintenanceRequests[0],'convertedWorkOrderId'),false)});
test('status transitions and illegal jump',()=>{const x=load();const w=x.api.createFromRequest('R1');assert.throws(()=>x.api.transition(w.id,'pending_inspection'));x.api.transition(w.id,'in_progress');x.api.transition(w.id,'pending_inspection');assert.equal(w.status,'pending_inspection');assert.throws(()=>x.api.transition(w.id,'closed'))});
test('cancel manager/admin only',()=>{const x=load('fleetOfficer');const w=x.api.createFromRequest('R1');assert.throws(()=>x.api.cancelWorkOrder(w.id,'x'));x.role('manager');assert.throws(()=>x.api.cancelWorkOrder(w.id,''));x.api.cancelWorkOrder(w.id,'x');assert.equal(w.status,'cancelled');assert.throws(()=>x.api.cancelWorkOrder(w.id,'x'))});
test('repair item cannot reach zero',()=>{const x=load();const w=x.api.createFromRequest('R1'),a=x.api.itemsFor(w.id)[0];assert.throws(()=>x.api.deleteRepairItem(a.id));const b=x.api.addRepairItem(w.id,{description:'Pad',qty:2});x.api.editRepairItem(b.id,{description:'Pad2',qty:2,status:'done'});assert.equal(b.status,'done');x.api.deleteRepairItem(a.id);assert.equal(x.api.itemsFor(w.id).length,1)});
test('permissions fail closed',()=>{const x=load('unknown');assert.equal(x.api.canView(),false);assert.equal(x.api.canManage(),false);assert.throws(()=>x.api.createFromRequest('R1'));x.role('viewer');assert.equal(x.api.canView(),true);assert.throws(()=>x.api.createFromRequest('R1'))});
test('audit entity is workOrder',()=>{const x=load();const w=x.api.createFromRequest('R1');x.api.transition(w.id,'in_progress');assert.ok(x.audits.every(a=>a.entity==='workOrder'));assert.deepEqual(x.audits.map(a=>a.action),['เปิดใบสั่งซ่อม','เริ่มซ่อมภายใน'])});
test('registry mixes legacy and new',()=>{const x=load();x.api.createFromRequest('R1');x.STATE.workOrders.push({id:'L1',workOrderNo:'LEG',assetId:'A1',maintenanceType:'repair',status:'closed',legacyImported:true});const h=x.api.workOrderRegistry(null);assert.match(h,/WO-0001/);assert.match(h,/LEG/);assert.match(h,/Legacy/);assert.match(h,/MR-1/);assert.doesNotMatch(h,/\+ งานซ่อม/)});
test('create button requires approval and keeps Batch5 panel',()=>{const x=load('admin',false);x.req.requestDetail('R1');assert.equal(x.api.appendCreateButton('R1'),false);x.approve(true);assert.equal(x.api.appendCreateButton('R1'),true);assert.match(x.content.innerHTML,/apdPanels/);assert.match(x.content.innerHTML,/woCreatePanel/)});
test('production API separate',()=>{const x=load();assert.notEqual(x.prod,x.api);assert.equal(typeof x.prod.workOrderRegistry,'function');assert.equal(typeof x.prod.workOrderDetail,'function')});
test('script order approval then workorder then parity',()=>{const h=fs.readFileSync('index.html','utf8');assert.ok(h.indexOf('approval-document.js')<h.indexOf('maintenance-v1-workorder.js'));assert.ok(h.indexOf('maintenance-v1-workorder.js')<h.indexOf('parity-baseline.js'))});
test('hub delegates and fallback remains',()=>{const src=fs.readFileSync('src/renderer/app/maintenance-v1-hub.js','utf8');function run(api){const host={innerHTML:''};let called=0;const c={STATE:{maintenance:[],pmPlans:[],workOrders:[{id:'W1',workOrderNo:'W1',assetId:'A1',status:'open'}]},CURRENT_ROLE:'admin',window:null,maintenancePage:()=>{},content:{innerHTML:''},setHead:()=>{},simpleTable:()=>'<table>fallback</table>',assetLabel:()=>'',$:()=>host,$$:()=>[]};c.window=c;if(api)c.FLEET_MAINTENANCE_WORKORDER_API={workOrderRegistry:h=>{called++;h.innerHTML='delegated'}};vm.createContext(c);vm.runInContext(src,c);return {c,host,get called(){return called}}}const a=run(true);assert.equal(a.c.FLEET_MAINTENANCE_HUB_TEST.jobsHtml(a.host),'');assert.equal(a.called,1);const b=run(false);assert.match(b.c.FLEET_MAINTENANCE_HUB_TEST.jobsHtml(b.host),/fallback/)});
