CREATE TABLE company (id TEXT PRIMARY KEY, code TEXT NOT NULL UNIQUE, name TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE site (id TEXT PRIMARY KEY, code TEXT NOT NULL UNIQUE, name TEXT NOT NULL, company_id TEXT, active INTEGER NOT NULL DEFAULT 1, FOREIGN KEY(company_id) REFERENCES company(id));
CREATE TABLE device (id TEXT PRIMARY KEY, device_code TEXT NOT NULL UNIQUE, site_id TEXT, name TEXT, authorized INTEGER NOT NULL DEFAULT 1, last_seen_at TEXT, FOREIGN KEY(site_id) REFERENCES site(id));
CREATE TABLE person (id TEXT PRIMARY KEY, person_code TEXT UNIQUE, employee_id TEXT, hr_employee_ref TEXT, display_name TEXT NOT NULL, company_id TEXT, department_name TEXT, position_name TEXT, work_email TEXT, phone TEXT, employment_status TEXT DEFAULT 'ACTIVE', source_system TEXT DEFAULT 'LOCAL', active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, FOREIGN KEY(company_id) REFERENCES company(id));
CREATE TABLE user_account (id TEXT PRIMARY KEY, person_id TEXT NOT NULL, login_email TEXT, system_role TEXT, data_scope TEXT, auth_provider TEXT DEFAULT 'LOCAL', active INTEGER NOT NULL DEFAULT 1, FOREIGN KEY(person_id) REFERENCES person(id));
CREATE TABLE owner_registry (id TEXT PRIMARY KEY, owner_code TEXT UNIQUE, owner_type TEXT NOT NULL, reference_type TEXT, reference_id TEXT, display_name TEXT NOT NULL, usage_classification TEXT NOT NULL DEFAULT 'UNVERIFIED', fuel_reimbursement_eligible INTEGER DEFAULT 0, repair_reimbursement_eligible INTEGER DEFAULT 0, authorization_start TEXT, authorization_end TEXT, note TEXT, active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE asset (id TEXT PRIMARY KEY, asset_code TEXT NOT NULL UNIQUE, name TEXT NOT NULL, asset_kind TEXT NOT NULL, company_id TEXT, site_id TEXT, owner_id TEXT, responsible_person_id TEXT, registration_no TEXT, status TEXT NOT NULL DEFAULT 'AVAILABLE', current_meter REAL DEFAULT 0, current_meter_unit TEXT NOT NULL DEFAULT 'KM', created_at TEXT NOT NULL, updated_at TEXT NOT NULL, version_no INTEGER NOT NULL DEFAULT 1, sync_status TEXT DEFAULT 'LOCAL', deleted_at TEXT, FOREIGN KEY(company_id) REFERENCES company(id), FOREIGN KEY(site_id) REFERENCES site(id), FOREIGN KEY(owner_id) REFERENCES owner_registry(id), FOREIGN KEY(responsible_person_id) REFERENCES person(id));
CREATE TABLE asset_document (id TEXT PRIMARY KEY, asset_id TEXT NOT NULL, document_type TEXT NOT NULL, document_no TEXT, issue_date TEXT, expiry_date TEXT, amount REAL, file_path TEXT, version_no INTEGER NOT NULL DEFAULT 1, previous_version_id TEXT, active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, deleted_at TEXT, FOREIGN KEY(asset_id) REFERENCES asset(id), FOREIGN KEY(previous_version_id) REFERENCES asset_document(id));
CREATE TABLE audit_log (id TEXT PRIMARY KEY, entity_type TEXT NOT NULL, entity_id TEXT, action TEXT NOT NULL, before_json TEXT, after_json TEXT, user_id TEXT, device_id TEXT, created_at TEXT NOT NULL);
