CREATE TABLE usage_request (
 id TEXT PRIMARY KEY, request_no TEXT NOT NULL UNIQUE, requester_person_id TEXT, requester_name TEXT NOT NULL, department_name TEXT, purpose TEXT NOT NULL, destination TEXT,
 planned_start_at TEXT NOT NULL, planned_end_at TEXT NOT NULL, requested_asset_id TEXT, assigned_asset_id TEXT, driver_operator_person_id TEXT,
 approval_status TEXT NOT NULL DEFAULT 'PENDING_DOCUMENT', usage_status TEXT NOT NULL DEFAULT 'DRAFT', approved_by_person_id TEXT, approved_by_name TEXT, approved_at TEXT, approval_document_ref TEXT,
 meter_before REAL, meter_unit TEXT DEFAULT 'KM', fuel_before TEXT, checked_out_at TEXT, returned_at TEXT, meter_after REAL, fuel_after TEXT, condition_after TEXT,
 incident_flag INTEGER NOT NULL DEFAULT 0, return_note TEXT, returned_by_name TEXT, received_by_name TEXT,
 created_at TEXT NOT NULL, updated_at TEXT NOT NULL, version_no INTEGER NOT NULL DEFAULT 1, sync_status TEXT DEFAULT 'LOCAL', deleted_at TEXT,
 FOREIGN KEY(requester_person_id) REFERENCES person(id), FOREIGN KEY(requested_asset_id) REFERENCES asset(id), FOREIGN KEY(assigned_asset_id) REFERENCES asset(id), FOREIGN KEY(driver_operator_person_id) REFERENCES person(id), FOREIGN KEY(approved_by_person_id) REFERENCES person(id)
);
CREATE INDEX idx_usage_period ON usage_request(planned_start_at,planned_end_at);
CREATE INDEX idx_usage_asset ON usage_request(assigned_asset_id,usage_status);
CREATE TABLE usage_status_history (id TEXT PRIMARY KEY, usage_request_id TEXT NOT NULL, status_type TEXT NOT NULL, from_status TEXT, to_status TEXT NOT NULL, note TEXT, changed_by TEXT, changed_at TEXT NOT NULL, FOREIGN KEY(usage_request_id) REFERENCES usage_request(id));
CREATE TABLE meter_reading (id TEXT PRIMARY KEY, asset_id TEXT NOT NULL, reading_value REAL NOT NULL, unit TEXT NOT NULL, reading_at TEXT NOT NULL, source_type TEXT NOT NULL, source_id TEXT, note TEXT, created_at TEXT NOT NULL, FOREIGN KEY(asset_id) REFERENCES asset(id));
CREATE TABLE vendor (id TEXT PRIMARY KEY, vendor_code TEXT UNIQUE, name TEXT NOT NULL, vendor_type TEXT, phone TEXT, active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE maintenance_work_order (id TEXT PRIMARY KEY, work_order_no TEXT UNIQUE, asset_id TEXT NOT NULL, maintenance_type TEXT NOT NULL, reported_at TEXT, opened_at TEXT, closed_at TEXT, meter_value REAL, meter_unit TEXT, symptom TEXT, diagnosis TEXT, vendor_id TEXT, status TEXT NOT NULL DEFAULT 'OPEN', total_cost REAL DEFAULT 0, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, version_no INTEGER NOT NULL DEFAULT 1, deleted_at TEXT, FOREIGN KEY(asset_id) REFERENCES asset(id), FOREIGN KEY(vendor_id) REFERENCES vendor(id));
CREATE TABLE maintenance_item (id TEXT PRIMARY KEY, work_order_id TEXT NOT NULL, item_type TEXT NOT NULL, description TEXT NOT NULL, quantity REAL DEFAULT 1, unit_cost REAL DEFAULT 0, amount REAL DEFAULT 0, FOREIGN KEY(work_order_id) REFERENCES maintenance_work_order(id));
CREATE TABLE pm_plan (id TEXT PRIMARY KEY, asset_id TEXT NOT NULL, name TEXT NOT NULL, trigger_type TEXT NOT NULL, interval_value REAL NOT NULL, interval_unit TEXT NOT NULL, last_service_at TEXT, last_meter REAL, next_due_at TEXT, next_due_meter REAL, active INTEGER NOT NULL DEFAULT 1, FOREIGN KEY(asset_id) REFERENCES asset(id));
CREATE TABLE fuel_transaction (id TEXT PRIMARY KEY, asset_id TEXT NOT NULL, usage_request_id TEXT, transaction_at TEXT NOT NULL, quantity REAL NOT NULL, unit TEXT NOT NULL DEFAULT 'LITER', unit_price REAL, amount REAL, meter_value REAL, fuel_type TEXT, vendor_id TEXT, receipt_no TEXT, created_at TEXT NOT NULL, deleted_at TEXT, FOREIGN KEY(asset_id) REFERENCES asset(id), FOREIGN KEY(usage_request_id) REFERENCES usage_request(id), FOREIGN KEY(vendor_id) REFERENCES vendor(id));
CREATE TABLE expense_ledger (id TEXT PRIMARY KEY, asset_id TEXT, expense_type TEXT NOT NULL, source_type TEXT NOT NULL, source_id TEXT, expense_date TEXT NOT NULL, amount REAL NOT NULL, vendor_id TEXT, description TEXT, created_at TEXT NOT NULL, deleted_at TEXT, FOREIGN KEY(asset_id) REFERENCES asset(id), FOREIGN KEY(vendor_id) REFERENCES vendor(id));
CREATE TABLE incident (id TEXT PRIMARY KEY, asset_id TEXT NOT NULL, usage_request_id TEXT, incident_at TEXT NOT NULL, incident_type TEXT NOT NULL, description TEXT, severity TEXT, status TEXT DEFAULT 'OPEN', created_at TEXT NOT NULL, updated_at TEXT NOT NULL, deleted_at TEXT, FOREIGN KEY(asset_id) REFERENCES asset(id), FOREIGN KEY(usage_request_id) REFERENCES usage_request(id));
