/* v0.13.4 minimum parity recovery: role context, menu permission, data scope, global search, notifications */
const PARITY_ROLES={admin:{name:'ผู้ดูแลระบบ',scope:'global'},manager:{name:'ผู้จัดการ/ผู้อนุมัติ',scope:'global'},clerk:{name:'เจ้าหน้าที่ธุรการ',scope:'unit'},fleetOfficer:{name:'เจ้าหน้าที่ยานยนต์',scope:'unit'},requester:{name:'ผู้ขอใช้งาน',scope:'unit'},viewer:{name:'ผู้ดูข้อมูล',scope:'unit'}};
const PARITY_MENU={admin:['dashboard','calendar','assets','documents','usage','maintenance','incidents','fuel','reports','people','masters','owners','org','audit','backup'],manager:['dashboard','calendar','assets','documents','usage','maintenance','incidents','fuel','reports','people'],clerk:['dashboard','calendar','assets','documents','usage'],fleetOfficer:['dashboard','calendar','assets','documents','usage','maintenance','incidents','fuel','reports','people'],requester:['dashboard','calendar','assets','usage','incidents'],viewer:['dashboard','calendar','assets','reports']};
let CURRENT_ROLE='admin',ACTIVE_COMPANY='ALL',ACTIVE_UNIT='ALL';
function parityEnsureState(){STATE.settings??={};STATE.settings.currentRole??='admin';STATE.settings.currentCompany??='ALL';STATE.settings.currentUnit??='ALL';STATE.notifications??=[];CURRENT_ROLE=STATE.settings.currentRole;ACTIVE_COMPANY=STATE.settings.currentCompany;ACTIVE_UNIT=STATE.settings.currentUnit;if(!PARITY_ROLES[CURRENT_ROLE])CURRENT_ROLE='admin';}
function parityAllowed(v){return (PARITY_MENU[CURRENT_ROLE]||[]).includes(v)}
function parityScopeAsset(a){if(PARITY_ROLES[CURRENT_ROLE]?.scope==='global'){return (ACTIVE_COMPANY==='ALL'||a.companyId===ACTIVE_COMPANY)&&(ACTIVE_UNIT==='ALL'||a.managingOperatingUnitId===ACTIVE_UNIT)}const account=(STATE.userAccounts||[]).find(x=>x.role===CURRENT_ROLE&&x.active!==false);const units=account?.operatingUnitIds?.length?account.operatingUnitIds:['OU-CENTRAL'];return units.includes(a.managingOperatingUnitId||'OU-CENTRAL')&&(ACTIVE_COMPANY==='ALL'||a.companyId===ACTIVE_COMPANY)}
function parityRoleGate(){const gate=$('#roleGate');if(!gate)return;$('#roleChoices').innerHTML=Object.entries(PARITY_ROLES).map(([id,r])=>`<button class="role-choice" data-role="${id}"><b>${r.name}</b><span>${r.scope==='global'?'เห็นข้อมูลตามขอบเขตส่วนกลาง':'เห็นเฉพาะหน่วยที่ได้รับสิทธิ์'}</span></button>`).join('');$$('[data-role]').forEach(b=>b.onclick=()=>{CURRENT_ROLE=b.dataset.role;STATE.settings.currentRole=CURRENT_ROLE;save(false);gate.classList.add('hidden');parityRefreshShell();go('dashboard')})}
function parityRefreshShell(){parityEnsureState();renderNav();const allowed=new Set(PARITY_MENU[CURRENT_ROLE]||[]);$$('.nav-btn').forEach(b=>b.classList.toggle('hidden',!allowed.has(b.dataset.v)));const r=PARITY_ROLES[CURRENT_ROLE];const su=$('#sideUser');if(su)su.innerHTML=`<div class="user-box"><b>${r.name}</b><small>${r.scope==='global'?'Global Data Scope':'Unit Data Scope'}</small><button id="switchRole" class="btn sm">สลับบทบาท</button></div>`;$('#switchRole')?.addEventListener('click',()=>$('#roleGate').classList.remove('hidden'));const co=$('#companyScope'),ou=$('#unitScope');if(co){co.innerHTML='<option value="ALL">ทุกบริษัท</option>'+STATE.companies.filter(x=>x.active!==false).map(x=>`<option value="${x.id}" ${x.id===ACTIVE_COMPANY?'selected':''}>${esc(x.name)}</option>`).join('');co.disabled=r.scope!=='global';co.onchange=()=>{ACTIVE_COMPANY=co.value;STATE.settings.currentCompany=ACTIVE_COMPANY;save(false);render()}}if(ou){ou.innerHTML='<option value="ALL">ทุกหน่วยดูแล</option>'+STATE.operatingUnits.filter(x=>x.active!==false).map(x=>`<option value="${x.id}" ${x.id===ACTIVE_UNIT?'selected':''}>${esc(x.name)}</option>`).join('');ou.disabled=r.scope!=='global';ou.onchange=()=>{ACTIVE_UNIT=ou.value;STATE.settings.currentUnit=ACTIVE_UNIT;save(false);render()}}parityNotifications();}
function parityNotifications(){const today0=new Date();const rows=(STATE.documents||[]).filter(d=>!d.deleted&&d.expiryDate).map(d=>({...d,days:Math.ceil((new Date(d.expiryDate)-today0)/864e5)})).filter(d=>d.days<=60);const n=$('#notificationCount');if(n)n.textContent=rows.length||'';const b=$('#notificationBtn');if(b)b.onclick=()=>{dialog.innerHTML=`<div class="dialog-head"><h2>การแจ้งเตือน</h2><button data-close>×</button></div><div>${rows.map(d=>{const a=STATE.assets.find(x=>x.id===d.assetId);return `<div class="notice-row"><b>${esc(a?.plate||a?.code||'-')}</b><span>${esc(d.title||d.type||'เอกสาร')} · ${d.days<0?'หมดอายุแล้ว':`เหลือ ${d.days} วัน`}</span><button class="btn sm" data-notice-asset="${esc(d.assetId)}">เปิดทรัพย์สิน</button></div>`}).join('')||'<div class="empty">ไม่มีการแจ้งเตือน</div>'}</div>`;modal.classList.remove('hidden');dialog.querySelector('[data-close]').onclick=closeModal;$$('[data-notice-asset]').forEach(x=>x.onclick=()=>{closeModal();assetDetailId=x.dataset.noticeAsset;assetTab='documents';render()})}}
function parityGlobalSearch(){const q=$('#globalSearch');if(!q)return;q.onkeydown=e=>{if(e.key!=='Enter')return;const s=q.value.trim().toLowerCase();if(!s)return;const a=(STATE.assets||[]).filter(parityScopeAsset).find(x=>`${x.code} ${x.plate} ${x.vin} ${x.brandName} ${x.modelName}`.toLowerCase().includes(s));if(a){assetDetailId=a.id;assetTab='general';render()}else toast('ไม่พบทรัพย์สิน',true)}}
const _goParity=go;go=v=>{if(!parityAllowed(v)){toast('บทบาทนี้ไม่มีสิทธิ์เปิดเมนูนี้',true);return}_goParity(v)};
const _assetsPageParity=assetsPage;assetsPage=function(){_assetsPageParity();const rows=STATE.assets.filter(x=>!x.deleted&&parityScopeAsset(x));const box=$('#assetRows');if(!box)return;const q=$('#assetQ'),co=$('#assetCo');const draw=()=>{const text=(q?.value||'').toLowerCase(),company=co?.value||'';const a=rows.filter(x=>(!company||x.companyId===company)&&`${x.code} ${x.plate} ${x.brandName} ${x.typeName}`.toLowerCase().includes(text));box.innerHTML=`<table><thead><tr><th>รหัส</th><th>ทะเบียน/ชื่อ</th><th>ประเภท</th><th>กรรมสิทธิ์</th><th>หน่วยดูแล</th><th>สถานะ</th><th>มิเตอร์</th></tr></thead><tbody>${a.map(x=>`<tr><td class="link" data-asset="${x.id}">${esc(x.code)}</td><td><b>${esc(x.plate||'-')}</b><div class="muted">${esc(x.brandName||'-')} ${esc(x.modelName||'')}</div></td><td>${esc(x.typeName||x.assetCategory)}</td><td>${esc(ownerName(x))}</td><td>${esc(ouName(x.managingOperatingUnitId))}</td><td>${pill(x.status)}</td><td>${money(x.mileage)} ${x.meterUnit==='hour'?'ชม.':'กม.'}</td></tr>`).join('')}</tbody></table>`;$$('[data-asset]').forEach(b=>b.onclick=()=>{assetDetailId=b.dataset.asset;assetTab='general';render()})};if(q)q.oninput=draw;if(co)co.onchange=draw;draw()};
setTimeout(()=>{parityEnsureState();parityRoleGate();parityRefreshShell();parityGlobalSearch();},30);
