const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const modal=$('#modal'),dialog=$('#dialog'),content=$('#content');let view='dashboard',STATE=null,assetDetailId='',assetTab='general',masterTab='vehicleTypes';
const now=()=>new Date().toISOString(),uid=p=>`${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`,today=()=>new Date().toISOString().slice(0,10),money=n=>Number(n||0).toLocaleString('th-TH',{minimumFractionDigits:0,maximumFractionDigits:2});
const NAV=[['ภาพรวม',[['dashboard','ภาพรวม'],['calendar','ปฏิทินการใช้งาน']]],['ทรัพย์สิน',[['assets','ทะเบียนทรัพย์สิน'],['documents','เอกสารประจำทรัพย์สิน']]],['การใช้งาน',[['usage','คำขอใช้รถ/เครื่องจักร']]],['บำรุงรักษา',[['maintenance','ซ่อมบำรุง / PM'],['incidents','อุบัติเหตุ/เหตุการณ์']]],['ต้นทุน',[['fuel','เชื้อเพลิง/ค่าใช้จ่าย'],['reports','รายงาน']]],['บุคลากร',[['people','พนักงานและผู้ใช้งาน']]],['ตั้งค่า',[['masters','ตั้งค่าข้อมูลทรัพย์สิน'],['owners','Owner Registry'],['org','บริษัท / หน่วยงาน / Site']]],['ระบบ',[['audit','Audit Log'],['backup','สำรอง/กู้คืน']]]];
const defaultMasters=()=>({vehicleTypes:[{id:'VT01',name:'รถยนต์/ยานพาหนะ',active:true},{id:'VT02',name:'รถบรรทุก',active:true}],machineryTypes:[{id:'MT01',name:'เครื่องจักรเกษตร',active:true},{id:'MT02',name:'รถแทรกเตอร์',active:true}],brands:[{id:'BR01',name:'Toyota',typeIds:['VT01','VT02'],active:true},{id:'BR02',name:'Mitsubishi',typeIds:['VT01','VT02'],active:true},{id:'BR03',name:'Isuzu',typeIds:['VT01','VT02'],active:true},{id:'BR04',name:'Kubota',typeIds:['MT01','MT02'],active:true},{id:'BR05',name:'Honda',typeIds:['VT01'],active:true}],models:[],colors:[{id:'CL01',name:'ขาว',brandIds:[],active:true},{id:'CL02',name:'ดำ',brandIds:[],active:true},{id:'CL03',name:'เงิน',brandIds:[],active:true}],bodyTypes:[{id:'BT01',name:'กระบะ',active:true},{id:'BT02',name:'เก๋ง',active:true},{id:'BT03',name:'ตู้',active:true},{id:'BT04',name:'แทรกเตอร์',active:true}],fuelTypes:[{id:'FT01',name:'ดีเซล',active:true},{id:'FT02',name:'เบนซิน',active:true},{id:'FT03',name:'ไฟฟ้า',active:true}],documentTypes:[{id:'DT01',name:'ภาษีรถ',key:'tax',active:true},{id:'DT02',name:'พ.ร.บ.',key:'act',active:true},{id:'DT03',name:'ประกันภัย',key:'insurance',active:true},{id:'DT04',name:'ตรวจสภาพ',key:'inspect',active:true},{id:'DT05',name:'เอกสารอื่น',key:'other',active:true}],insuranceCompanies:[{id:'IN01',name:'วิริยะประกันภัย',active:true},{id:'IN02',name:'กรุงเทพประกันภัย',active:true}]});
const companies=[['CBG-HQ','CBH','บริษัท งานทวีพี่น้อง จำกัด'],['CBG-LOG','NRP','บริษัท สวนยางงานทวี จำกัด'],['CBS','CBS','บริษัท งานทวีบริการ จำกัด'],['PP','PP','บริษัท สวนภูเก็ต 2011 จำกัด'],['CBE','CBE','บริษัท ซี.บี.เอสเตท จำกัด'],['CBP','CBP','บริษัท ซี.บี.พรอพเพอร์ตี้ จำกัด'],['HDM','HDM','บริษัท เรือขุดแร่หาดใหญ่']].map(x=>({id:x[0],code:x[1],name:x[2],active:true}));
function ownerName(v){return STATE.ownerRegistry.find(x=>x.id===v.ownerId)?.displayName||'-'} function coName(id){return STATE.companies.find(x=>x.id===id)?.name||'-'} function personName(id){return STATE.people.find(x=>x.id===id)?.name||'-'} function ouName(id){return STATE.operatingUnits.find(x=>x.id===id)?.name||'-'};
async function init(){let raw=window.fleetDesktop?.load();if(raw){try{STATE=JSON.parse(raw)}catch(_){}}if(!STATE){const seed=window.SEED90||[];STATE=seedState(seed);save(false)}migrateState();renderNav();window.fleetDesktop?.info().then(i=>$('#dbPath').textContent=i.dbPath||'');go('dashboard');}
function seedState(seed){const assets=seed.map(v=>({id:v.id,code:v.code,plate:v.plate,province:v.province,typeName:v.type,assetCategory:v.assetCategory,companyId:v.companyId,brandName:v.brand,modelName:v.model,colorName:v.color,modelYear:v.year,vin:v.vin,engineNo:v.engineNo,fuelTypeName:v.fuelType,mileage:Number(v.mileage||0),meterUnit:v.meterUnit||'km',seats:v.seats,purchaseDate:v.purchaseDate,purchasePrice:Number(v.purchasePrice||0),responsibleText:v.responsible,status:v.status||'available',note:v.note,sourceOwner:v.sourceOwner,sourceCaretaker:v.sourceCaretaker,ownerId:'',responsiblePersonId:'',homeOperatingUnitId:'OU-CENTRAL',managingOperatingUnitId:'OU-CENTRAL',deptId:'',locationId:'',brandId:'',modelId:'',colorId:'',bodyTypeId:'',fuelTypeId:'',photos:[],deleted:false,createdAt:now(),updatedAt:now()}));return {version:'0.4.2',companies,operatingUnits:[{id:'OU-CENTRAL',code:'CENTRAL',name:'ส่วนกลาง',companyId:'CBG-HQ',active:true}],departments:[],locations:[],people:[{id:'PER01',code:'PER01',employeeId:'',name:'สรรัฐ งานทวี',companyId:'CBG-HQ',deptId:'',position:'',email:'',phone:'',roles:['assetOwner'],source:'LOCAL',active:true},{id:'PER02',code:'PER02',employeeId:'',name:'ธำรงค์ งานทวี',companyId:'CBS',deptId:'',position:'',email:'',phone:'',roles:['assetOwner'],source:'LOCAL',active:true}],userAccounts:[{id:'UA-ADMIN',personId:'',loginEmail:'admin@local',role:'admin',dataScope:'all',authProvider:'local',operatingUnitIds:['OU-CENTRAL'],active:true}],ownerRegistry:[],assets,documents:[],usage:[],maintenance:[],pmPlans:[],fuel:[],expenses:[],incidents:[],audit:[],masters:defaultMasters()};}
function migrateState(){for(const k of ['companies','operatingUnits','departments','locations','people','userAccounts','ownerRegistry','assets','documents','usage','maintenance','pmPlans','fuel','expenses','incidents','audit'])STATE[k]??=[];STATE.masters??=defaultMasters();if(!STATE.ownerRegistry.length){STATE.companies.forEach((c,i)=>STATE.ownerRegistry.push({id:`OW${String(i+1).padStart(2,'0')}`,ownerType:'company',referenceId:c.id,displayName:c.name,usageClass:'company_owned',fuelEligible:true,repairEligible:true,active:true}));STATE.ownerRegistry.push({id:'OW90',ownerType:'person',referenceId:'PER01',displayName:'สรรัฐ งานทวี',usageClass:'private_for_work',fuelEligible:true,repairEligible:true,active:true},{id:'OW91',ownerType:'person',referenceId:'PER02',displayName:'ธำรงค์ งานทวี',usageClass:'private_for_work',fuelEligible:true,repairEligible:true,active:true},{id:'OW99',ownerType:'other',referenceId:'',displayName:'กรรมสิทธิ์อื่น / รอตรวจสอบ',usageClass:'unverified',fuelEligible:false,repairEligible:false,active:true});STATE.assets.forEach(a=>{const o=STATE.ownerRegistry.find(x=>x.referenceId===a.companyId);if(o&&!a.ownerId)a.ownerId=o.id})}STATE.version='0.4.2';save(false);}
function save(audit=true,action='',entity='',id='',before=null,after=null){if(audit&&action)STATE.audit.unshift({id:uid('LOG'),ts:now(),user:'Desktop Admin',action,entity,recordId:id,before,after});window.fleetDesktop?.save(JSON.stringify(STATE));}
function toast(msg,err=false){const d=document.createElement('div');d.className='toast'+(err?' err':'');d.textContent=msg;$('#toast').appendChild(d);setTimeout(()=>d.remove(),2600)} function closeModal(){modal.classList.add('hidden');dialog.innerHTML=''}
function formModal(title,html,onSave,wide=true){dialog.innerHTML=`<div class="dialog-head"><h2>${title}</h2><button data-close>×</button></div><form class="form-grid">${html}<div class="actions wide"><button type="button" class="btn" data-close>ยกเลิก</button><button class="btn primary">บันทึก</button></div></form>`;modal.classList.remove('hidden');dialog.querySelectorAll('[data-close]').forEach(x=>x.onclick=closeModal);dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();try{await onSave(Object.fromEntries(new FormData(e.target)));closeModal();render();toast('บันทึกเรียบร้อย')}catch(x){toast(x.message||String(x),true)}}}
function renderNav(){$('#nav').innerHTML=NAV.map(([s,items])=>`<div class="nav-sec">${s}</div>${items.map(([v,t])=>`<button class="nav-btn" data-v="${v}">${t}</button>`).join('')}`).join('');$$('.nav-btn').forEach(b=>b.onclick=()=>go(b.dataset.v));}
function go(v){view=v;assetDetailId='';$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.v===v));render();}
function render(){const map={dashboard:dashboardPage,calendar:calendarPage,assets:assetsPage,documents:documentPage,usage:usagePage,maintenance:maintenancePage,incidents:incidentPage,fuel:fuelPage,reports:reportsPage,people:peoplePage,masters:settingsPage,owners:ownersPage,org:orgPage,audit:auditPage,backup:backupPage};if(assetDetailId)return assetProfile(assetDetailId);(map[view]||dashboardPage)();}
function setHead(t,s='Fleet & Machinery Management'){$('#title').textContent=t;$('#subtitle').textContent=s}
function dashboardPage(){setHead('ภาพรวม');const active=STATE.assets.filter(x=>!x.deleted),exp=STATE.documents.filter(d=>!d.deleted&&d.expiryDate&&new Date(d.expiryDate)<new Date()),near=STATE.documents.filter(d=>!d.deleted&&d.expiryDate&&new Date(d.expiryDate)>=new Date()&&(new Date(d.expiryDate)-new Date())/864e5<=60);content.innerHTML=`<div class="cards"><div class="card"><span class="muted">ทรัพย์สิน</span><b>${active.length}</b></div><div class="card"><span class="muted">พร้อมใช้งาน</span><b>${active.filter(x=>x.status==='available').length}</b></div><div class="card"><span class="muted">เอกสารใกล้หมดอายุ</span><b>${near.length}</b></div><div class="card"><span class="muted">เอกสารหมดอายุ</span><b>${exp.length}</b></div></div><div class="panel"><h3>Fleet Desktop v0.4.2 — Parity Correction</h3><p>ฐานทรัพย์สิน 90 รายการ + Asset Profile/Documents/Master/Owner/Person/Audit และ Workflow Usage/Maintenance/Fuel สำหรับทดสอบ Offline</p></div>`}
function calendarPage(){setHead('ปฏิทินการใช้งาน');const rows=STATE.usage.filter(x=>!['cancelled','rejected'].includes(x.status)).sort((a,b)=>(a.startAt||'').localeCompare(b.startAt||''));content.innerHTML=`<div class="panel"><div class="toolbar"><h3>รายการใช้งานตามวัน</h3></div>${rows.length?`<table><thead><tr><th>วันที่</th><th>เลขที่</th><th>ผู้ขอ</th><th>ทรัพย์สิน</th><th>สถานะ</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.startAt||'-')} – ${esc(x.endAt||'-')}</td><td>${esc(x.no)}</td><td>${esc(x.requesterName)}</td><td>${esc(STATE.assets.find(a=>a.id===x.assignedAssetId)?.plate||'-')}</td><td>${pill(x.status)}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">ยังไม่มีรายการใช้งาน</div>'}</div>`}
const pill=s=>`<span class="pill ${['available','closed','returned','approved','done'].includes(s)?'ok':['expired','rejected','damage'].includes(s)?'bad':'warn'}">${esc(s||'-')}</span>`;
