const $=s=>document.querySelector(s);
const content=$('#content'), title=$('#pageTitle'), modal=$('#modal'), dialog=$('#dialog');
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmt=d=>d?new Date(d).toLocaleString('th-TH'):'-';
const val=(v,d='')=>v??d;
let currentPage='dashboard';
let cache={assets:[],people:[],companies:[],sites:[],owners:[]};

function notice(msg,type='ok'){ const n=document.createElement('div');n.className=`notice ${type}`;n.textContent=msg;document.body.appendChild(n);setTimeout(()=>n.remove(),2800); }
function closeModal(){ modal.classList.add('hidden'); dialog.innerHTML=''; }
function openModal(html,onSubmit){ dialog.innerHTML=html; modal.classList.remove('hidden'); dialog.querySelector('[data-close]')?.addEventListener('click',closeModal); const f=dialog.querySelector('form'); if(f&&onSubmit)f.addEventListener('submit',async e=>{e.preventDefault();try{await onSubmit(Object.fromEntries(new FormData(f)));closeModal();await navigate(currentPage);notice('บันทึกข้อมูลเรียบร้อย');}catch(err){notice(err.message||String(err),'error');}}); }
async function masters(){ const [people,companies,sites,owners]=await Promise.all([window.fleet.listPeople(),window.fleet.listCompanies(),window.fleet.listSites(),window.fleet.listOwners()]); cache={...cache,people,companies,sites,owners}; return cache; }
const opts=(arr,selected,label='name')=>'<option value="">- ไม่ระบุ -</option>'+arr.map(x=>`<option value="${esc(x.id)}" ${x.id===selected?'selected':''}>${esc(x[label]||x.display_name||x.code)}</option>`).join('');

async function dashboard(){ const s=await window.fleet.dashboard(); title.textContent='ภาพรวม'; content.innerHTML=`<div class="cards"><div class="card"><span class="muted">ทรัพย์สินทั้งหมด</span><b>${s.assets}</b></div><div class="card"><span class="muted">พร้อมใช้งาน</span><b>${s.available}</b></div><div class="card"><span class="muted">รายการใช้งานที่ยังไม่ปิด</span><b>${s.usageOpen}</b></div><div class="card"><span class="muted">งานซ่อมที่ยังไม่ปิด</span><b>${s.maintenanceOpen}</b></div></div><div class="panel"><h3>Fleet Desktop v0.2.0 — Functional MVP</h3><p>ใช้งานแบบ Offline ด้วย SQLite บนเครื่องนี้</p><div class="quick"><button class="primary" data-go="assets">จัดการทรัพย์สิน</button><button data-go="usage">บันทึกการใช้รถ/เครื่องจักร</button><button data-go="people">พนักงานและผู้ใช้งาน</button><button data-go="settings">ตั้งค่า Master</button></div></div>`; content.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>selectNav(b.dataset.go)); }

async function assetsPage(){ title.textContent='ทรัพย์สิน'; cache.assets=await window.fleet.listAssets(''); content.innerHTML=`<div class="panel"><div class="toolbar"><div><b>ทะเบียนรถและเครื่องจักร</b><div class="muted">เพิ่ม แก้ไข และติดตามเลขไมล์/ชั่วโมง</div></div><button class="primary" id="addAsset">+ เพิ่มทรัพย์สิน</button></div><div class="filters"><input id="assetSearch" placeholder="ค้นหารหัส ชื่อ หรือทะเบียน"></div><div id="assetTable"></div></div>`;
 const render=()=>{$('#assetTable').innerHTML=cache.assets.length?`<table><thead><tr><th>รหัส</th><th>ชื่อ/ทะเบียน</th><th>ประเภท</th><th>เจ้าของ/ผู้รับผิดชอบ</th><th>สถานะ</th><th>เลขไมล์/ชม.</th><th></th></tr></thead><tbody>${cache.assets.map(a=>`<tr><td><b>${esc(a.asset_code)}</b></td><td>${esc(a.name)}<div class="muted">${esc(a.registration_no||'-')}</div></td><td>${esc(a.asset_kind)}</td><td>${esc(a.owner_name||'-')}<div class="muted">${esc(a.responsible_name||'')}</div></td><td><span class="status ${a.status==='AVAILABLE'?'green':''}">${esc(a.status)}</span></td><td>${esc(a.current_meter)} ${esc(a.current_meter_unit)}</td><td class="row-actions"><button data-edit="${a.id}">แก้ไข</button><button class="danger-link" data-del="${a.id}">ลบ</button></td></tr>`).join('')}</tbody></table>`:'<div class="empty">ยังไม่มีทรัพย์สิน กด “เพิ่มทรัพย์สิน” เพื่อเริ่มต้น</div>'; bind();};
 const bind=()=>{document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>assetModal(cache.assets.find(x=>x.id===b.dataset.edit)));document.querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{if(!confirm('ยืนยันการลบทรัพย์สินนี้?'))return;try{await window.fleet.deleteAsset(b.dataset.del);await assetsPage();notice('ลบข้อมูลแล้ว');}catch(e){notice(e.message,'error')}})};
 $('#addAsset').onclick=()=>assetModal(); $('#assetSearch').oninput=async e=>{cache.assets=await window.fleet.listAssets(e.target.value);render();}; render(); }
async function assetModal(a={}){ await masters(); openModal(`<div class="dialog-head"><h2>${a.id?'แก้ไข':'เพิ่ม'}ทรัพย์สิน</h2><button data-close>×</button></div><form><input type="hidden" name="id" value="${esc(a.id||'')}"><label>รหัสทรัพย์สิน<input name="asset_code" required value="${esc(a.asset_code||'')}"></label><label>ชื่อรถ/เครื่องจักร<input name="name" required value="${esc(a.name||'')}"></label><label>ประเภท<select name="asset_kind"><option ${a.asset_kind==='VEHICLE'?'selected':''}>VEHICLE</option><option ${a.asset_kind==='MACHINERY'?'selected':''}>MACHINERY</option><option ${a.asset_kind==='EQUIPMENT'?'selected':''}>EQUIPMENT</option></select></label><label>ทะเบียน<input name="registration_no" value="${esc(a.registration_no||'')}"></label><label>บริษัท<select name="company_id">${opts(cache.companies,a.company_id)}</select></label><label>Site<select name="site_id">${opts(cache.sites,a.site_id)}</select></label><label>เจ้าของ<select name="owner_id">${opts(cache.owners,a.owner_id,'display_name')}</select></label><label>ผู้รับผิดชอบ<select name="responsible_person_id">${opts(cache.people,a.responsible_person_id,'display_name')}</select></label><label>เลขไมล์/ชั่วโมง<input type="number" step="0.01" name="current_meter" value="${val(a.current_meter,0)}"></label><label>หน่วย<select name="current_meter_unit"><option ${a.current_meter_unit!=='HOUR'?'selected':''}>KM</option><option ${a.current_meter_unit==='HOUR'?'selected':''}>HOUR</option></select></label><label>สถานะ<select name="status"><option value="AVAILABLE" ${a.status==='AVAILABLE'?'selected':''}>พร้อมใช้งาน</option><option value="MAINTENANCE" ${a.status==='MAINTENANCE'?'selected':''}>ซ่อมบำรุง</option><option value="IN_USE" ${a.status==='IN_USE'?'selected':''}>กำลังใช้งาน</option><option value="INACTIVE" ${a.status==='INACTIVE'?'selected':''}>ไม่ใช้งาน</option></select></label><div class="actions wide"><button type="button" data-close>ยกเลิก</button><button class="primary">บันทึก</button></div></form>`,p=>window.fleet.saveAsset(p)); }

async function usagePage(){ title.textContent='การใช้รถ/เครื่องจักร'; const list=await window.fleet.listUsage(); content.innerHTML=`<div class="panel"><div class="toolbar"><div><b>คำขอและการใช้งาน</b><div class="muted">แจ้งจอง → พิมพ์ใบขอ → อนุมัติ → ใช้งาน → คืนรถ</div></div><button class="primary" id="newUsage">+ บันทึกคำขอ</button></div>${list.length?`<table><thead><tr><th>เลขที่</th><th>ผู้ขอ/วัตถุประสงค์</th><th>ช่วงเวลา</th><th>รถที่จัด</th><th>อนุมัติ</th><th>สถานะ</th><th></th></tr></thead><tbody>${list.map(u=>`<tr><td><b>${esc(u.request_no)}</b></td><td>${esc(u.requester_name)}<div class="muted">${esc(u.purpose)}</div></td><td>${fmt(u.planned_start_at)}<br>${fmt(u.planned_end_at)}</td><td>${esc(u.assigned_asset_code||'ยังไม่จัดสรร')}<div class="muted">${esc(u.assigned_asset_name||'')}</div></td><td>${esc(u.approval_status)}</td><td><span class="status">${esc(u.usage_status)}</span></td><td class="row-actions"><button data-print="${u.id}">พิมพ์</button>${u.approval_status!=='APPROVED_EXTERNAL'?`<button data-approve="${u.id}">อนุมัติ</button>`:''}${u.usage_status!=='CLOSED'?`<button data-return="${u.id}">คืนรถ</button>`:''}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">ยังไม่มีคำขอใช้รถ/เครื่องจักร</div>'}</div>`;
 $('#newUsage').onclick=usageModal; document.querySelectorAll('[data-approve]').forEach(b=>b.onclick=()=>approvalModal(b.dataset.approve)); document.querySelectorAll('[data-return]').forEach(b=>b.onclick=()=>returnModal(b.dataset.return)); document.querySelectorAll('[data-print]').forEach(b=>b.onclick=()=>printUsage(b.dataset.print)); }
async function usageModal(){ cache.assets=await window.fleet.listAssets(''); const available=cache.assets.filter(a=>a.status==='AVAILABLE'); openModal(`<div class="dialog-head"><h2>บันทึกคำขอใช้รถ/เครื่องจักร</h2><button data-close>×</button></div><form><label>ผู้ขอใช้<input name="requester_name" required></label><label>หน่วยงาน<input name="department_name"></label><label class="wide">วัตถุประสงค์<input name="purpose" required></label><label class="wide">สถานที่/ปลายทาง<input name="destination"></label><label>เริ่มใช้<input type="datetime-local" name="planned_start_at" required></label><label>สิ้นสุด<input type="datetime-local" name="planned_end_at" required></label><label class="wide">รถ/เครื่องจักรที่ต้องการ<select name="assigned_asset_id">${opts(available,null)}</select></label><div class="actions wide"><button type="button" data-close>ยกเลิก</button><button class="primary">บันทึกคำขอ</button></div></form>`,async p=>{if(p.assigned_asset_id&&await window.fleet.checkConflict({assetId:p.assigned_asset_id,start:p.planned_start_at,end:p.planned_end_at}))throw new Error('รถ/เครื่องจักรมีรายการใช้งานซ้อนช่วงเวลานี้');return window.fleet.createUsage(p);}); }
async function approvalModal(id){ const u=await window.fleet.getUsage(id); cache.assets=await window.fleet.listAssets(''); openModal(`<div class="dialog-head"><h2>บันทึกผลอนุมัติ ${esc(u.request_no)}</h2><button data-close>×</button></div><form><input type="hidden" name="id" value="${id}"><input type="hidden" name="approval_status" value="APPROVED_EXTERNAL"><input type="hidden" name="usage_status" value="ASSIGNED"><label>ผู้อนุมัติ<input name="approved_by_name" required></label><label>วันที่อนุมัติ<input type="datetime-local" name="approved_at" required></label><label>รถ/เครื่องจักรที่จัด<select name="assigned_asset_id" required>${opts(cache.assets.filter(a=>a.status==='AVAILABLE'||a.id===u.assigned_asset_id),u.assigned_asset_id)}</select></label><label>เลขไมล์/ชั่วโมงก่อนใช้<input type="number" step="0.01" name="meter_before" required value="${val(u.meter_before,'')}"></label><label>ระดับเชื้อเพลิงก่อนใช้<input name="fuel_before" placeholder="เช่น 3/4"></label><label>เลขที่/อ้างอิงเอกสาร<input name="approval_document_ref"></label><div class="actions wide"><button type="button" data-close>ยกเลิก</button><button class="primary">บันทึกผลอนุมัติ</button></div></form>`,p=>window.fleet.updateUsageStatus(p)); }
async function returnModal(id){ const u=await window.fleet.getUsage(id); openModal(`<div class="dialog-head"><h2>บันทึกการคืน ${esc(u.request_no)}</h2><button data-close>×</button></div><form><input type="hidden" name="id" value="${id}"><label>วันเวลาคืน<input type="datetime-local" name="returned_at" required></label><label>เลขไมล์/ชั่วโมงหลังใช้<input type="number" step="0.01" name="meter_after" required></label><label>เชื้อเพลิงหลังคืน<input name="fuel_after" placeholder="เช่น 1/2"></label><label>สภาพหลังใช้<select name="condition_after"><option value="NORMAL">ปกติ</option><option value="DAMAGE">มีความเสียหาย/ผิดปกติ</option></select></label><label>ผู้คืน<input name="returned_by_name"></label><label>ผู้รับคืน<input name="received_by_name"></label><label class="wide">หมายเหตุ/ความเสียหาย<textarea name="return_note"></textarea></label><label class="check wide"><input type="checkbox" name="incident_flag" value="1"> พบเหตุผิดปกติ/อุบัติเหตุ</label><div class="actions wide"><button type="button" data-close>ยกเลิก</button><button class="primary">บันทึกคืนและปิดงาน</button></div></form>`,p=>window.fleet.recordReturn({...p,incident_flag:!!p.incident_flag})); }
async function printUsage(id){ const u=await window.fleet.getUsage(id); const old=content.innerHTML; const oldTitle=title.textContent; title.textContent='ใบขอใช้รถ/เครื่องจักร'; content.innerHTML=`<div class="print-sheet"><div class="print-head"><h2>ใบขอใช้รถ/เครื่องจักร</h2><b>${esc(u.request_no)}</b></div><h3>1. ข้อมูลคำขอ</h3><div class="print-grid"><div><b>ผู้ขอ:</b> ${esc(u.requester_name)}</div><div><b>หน่วยงาน:</b> ${esc(u.department_name||'-')}</div><div class="wide"><b>วัตถุประสงค์:</b> ${esc(u.purpose)}</div><div class="wide"><b>ปลายทาง:</b> ${esc(u.destination||'-')}</div><div><b>เริ่มใช้:</b> ${fmt(u.planned_start_at)}</div><div><b>สิ้นสุด:</b> ${fmt(u.planned_end_at)}</div></div><h3>2. ข้อมูลรถก่อนใช้งาน</h3><div class="print-grid"><div><b>รถ/เครื่องจักร:</b> ${esc(u.assigned_asset_code||'....................')}</div><div><b>ทะเบียน:</b> ${esc(u.registration_no||'....................')}</div><div><b>เลขไมล์/ชั่วโมงก่อนใช้:</b> ${esc(u.meter_before??'....................')}</div><div><b>เชื้อเพลิงก่อนใช้:</b> ${esc(u.fuel_before||'....................')}</div></div><h3>3. การอนุมัติ</h3><div class="signature-row"><div>□ อนุมัติ &nbsp; □ ไม่อนุมัติ<br><br>ผู้อนุมัติ ........................................<br>วันที่ ........................................</div></div><h3>4. ข้อมูลการคืน</h3><div class="print-grid"><div>วันเวลาคืน ........................................</div><div>เลขไมล์/ชั่วโมงหลังใช้ ................................</div><div>เชื้อเพลิงหลังคืน ....................................</div><div>สภาพหลังใช้ □ ปกติ □ มีปัญหา</div><div class="wide">ความเสียหาย/หมายเหตุ ....................................................................................................</div><div>ผู้คืน ........................................</div><div>ผู้รับคืน ........................................</div></div></div>`; setTimeout(()=>{window.print();title.textContent=oldTitle;content.innerHTML=old;navigate('usage');},200); }

async function peoplePage(){ title.textContent='พนักงานและผู้ใช้งาน'; cache.people=await window.fleet.listPeople(); content.innerHTML=`<div class="panel"><div class="toolbar"><div><b>Person / Employee Master</b><div class="muted">รองรับ Local และเตรียมเชื่อม HR</div></div><button class="primary" id="addPerson">+ เพิ่มบุคคล</button></div>${cache.people.length?`<table><thead><tr><th>รหัส</th><th>ชื่อ</th><th>หน่วยงาน/ตำแหน่ง</th><th>ติดต่อ</th><th>สถานะ</th><th></th></tr></thead><tbody>${cache.people.map(p=>`<tr><td>${esc(p.employee_id||p.person_code||'-')}</td><td><b>${esc(p.display_name)}</b><div class="muted">${esc(p.source_system)}</div></td><td>${esc(p.department_name||'-')}<div class="muted">${esc(p.position_name||'')}</div></td><td>${esc(p.work_email||'-')}<div class="muted">${esc(p.phone||'')}</div></td><td>${esc(p.employment_status)}</td><td><button data-person="${p.id}">แก้ไข</button></td></tr>`).join('')}</tbody></table>`:'<div class="empty">ยังไม่มีข้อมูลบุคลากร</div>'}</div>`; $('#addPerson').onclick=()=>personModal(); document.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>personModal(cache.people.find(x=>x.id===b.dataset.person))); }
function personModal(p={}){ openModal(`<div class="dialog-head"><h2>${p.id?'แก้ไข':'เพิ่ม'}บุคลากร</h2><button data-close>×</button></div><form><input type="hidden" name="id" value="${esc(p.id||'')}"><label>Person Code<input name="person_code" value="${esc(p.person_code||'')}"></label><label>รหัสพนักงาน<input name="employee_id" value="${esc(p.employee_id||'')}"></label><label class="wide">ชื่อ-นามสกุล<input name="display_name" required value="${esc(p.display_name||'')}"></label><label>หน่วยงาน<input name="department_name" value="${esc(p.department_name||'')}"></label><label>ตำแหน่ง<input name="position_name" value="${esc(p.position_name||'')}"></label><label>อีเมล<input name="work_email" value="${esc(p.work_email||'')}"></label><label>โทรศัพท์<input name="phone" value="${esc(p.phone||'')}"></label><label>สถานะ<select name="employment_status"><option value="ACTIVE">ACTIVE</option><option value="TERMINATED" ${p.employment_status==='TERMINATED'?'selected':''}>TERMINATED</option></select></label><div class="actions wide"><button type="button" data-close>ยกเลิก</button><button class="primary">บันทึก</button></div></form>`,x=>window.fleet.savePerson(x)); }

async function settingsPage(){ title.textContent='ตั้งค่า'; await masters(); content.innerHTML=`<div class="tabs"><button class="active" data-tab="company">บริษัท</button><button data-tab="site">Site</button><button data-tab="owner">Owner Registry</button><button data-tab="backup">สำรอง/กู้คืน</button></div><div id="settingsBody"></div>`; const show=tab=>{document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab)); if(tab==='company')companySettings();if(tab==='site')siteSettings();if(tab==='owner')ownerSettings();if(tab==='backup')backupSettings();};document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>show(b.dataset.tab));show('company'); }
function companySettings(){ $('#settingsBody').innerHTML=`<div class="panel"><div class="toolbar"><b>บริษัท</b><button class="primary" id="addCompany">+ เพิ่มบริษัท</button></div>${cache.companies.map(c=>`<div class="list-row"><b>${esc(c.code)}</b><span>${esc(c.name)}</span></div>`).join('')||'<div class="empty">ยังไม่มีบริษัท</div>'}</div>`;$('#addCompany').onclick=()=>openModal(`<div class="dialog-head"><h2>เพิ่มบริษัท</h2><button data-close>×</button></div><form><label>รหัส<input name="code" required></label><label>ชื่อบริษัท<input name="name" required></label><div class="actions wide"><button type="button" data-close>ยกเลิก</button><button class="primary">บันทึก</button></div></form>`,p=>window.fleet.saveCompany(p)); }
function siteSettings(){ $('#settingsBody').innerHTML=`<div class="panel"><div class="toolbar"><b>Site / หน่วยปฏิบัติการ</b><button class="primary" id="addSite">+ เพิ่ม Site</button></div>${cache.sites.map(s=>`<div class="list-row"><b>${esc(s.code)}</b><span>${esc(s.name)} · ${esc(s.company_name||'-')}</span></div>`).join('')||'<div class="empty">ยังไม่มี Site</div>'}</div>`;$('#addSite').onclick=()=>openModal(`<div class="dialog-head"><h2>เพิ่ม Site</h2><button data-close>×</button></div><form><label>รหัส<input name="code" required></label><label>ชื่อ Site<input name="name" required></label><label class="wide">บริษัท<select name="company_id">${opts(cache.companies)}</select></label><div class="actions wide"><button type="button" data-close>ยกเลิก</button><button class="primary">บันทึก</button></div></form>`,p=>window.fleet.saveSite(p)); }
function ownerSettings(){ $('#settingsBody').innerHTML=`<div class="panel"><div class="toolbar"><b>Owner Registry</b><button class="primary" id="addOwner">+ เพิ่มเจ้าของ</button></div>${cache.owners.map(o=>`<div class="list-row"><b>${esc(o.owner_code||o.owner_type)}</b><span>${esc(o.display_name)} · ${esc(o.usage_classification)}</span></div>`).join('')||'<div class="empty">ยังไม่มี Owner Registry</div>'}</div>`;$('#addOwner').onclick=()=>openModal(`<div class="dialog-head"><h2>เพิ่ม Owner Registry</h2><button data-close>×</button></div><form><label>Owner Code<input name="owner_code"></label><label>ประเภท<select name="owner_type"><option>COMPANY</option><option>EMPLOYEE</option><option>PERSON</option><option>EXTERNAL</option><option>OTHER</option></select></label><label class="wide">ชื่อแสดง<input name="display_name" required></label><label>การใช้งาน<select name="usage_classification"><option value="COMPANY_OWNED">บริษัทเป็นเจ้าของ</option><option value="PRIVATE_FOR_WORK">รถส่วนตัวใช้ในงาน</option><option value="UNVERIFIED">รอตรวจสอบ</option></select></label><label>หมายเหตุ<input name="note"></label><label class="check"><input type="checkbox" name="fuel_reimbursement_eligible" value="1"> เบิกเชื้อเพลิงได้</label><label class="check"><input type="checkbox" name="repair_reimbursement_eligible" value="1"> เบิกค่าซ่อมได้</label><div class="actions wide"><button type="button" data-close>ยกเลิก</button><button class="primary">บันทึก</button></div></form>`,p=>window.fleet.saveOwner({...p,fuel_reimbursement_eligible:!!p.fuel_reimbursement_eligible,repair_reimbursement_eligible:!!p.repair_reimbursement_eligible})); }
function backupSettings(){ $('#settingsBody').innerHTML=`<div class="panel"><h3>สำรองและกู้คืนฐานข้อมูล</h3><p class="muted">สำรอง SQLite ก่อนอัปเดตเวอร์ชันหรือย้ายเครื่อง</p><div class="quick"><button class="primary" id="backup2">สำรองฐานข้อมูล</button><button id="restore2">กู้คืนจากไฟล์สำรอง</button></div></div>`;$('#backup2').onclick=backup;$('#restore2').onclick=restore; }
function foundation(name,desc){ title.textContent=name; content.innerHTML=`<div class="panel"><h3>${name}</h3><p>${desc}</p><p class="muted">วาง Database Schema ไว้แล้ว และจะเปิด Workflow ในเวอร์ชันถัดไป</p></div>`; }
async function backup(){const r=await window.fleet.backup();if(r?.ok)notice('สำรองข้อมูลแล้ว: '+r.path);}
async function restore(){if(!confirm('การกู้คืนจะเขียนทับฐานข้อมูลปัจจุบัน ควรสำรองข้อมูลก่อน ยืนยันหรือไม่?'))return;const r=await window.fleet.restore();if(r?.ok){notice('กู้คืนข้อมูลเรียบร้อย');await navigate(currentPage);}}
async function navigate(p){currentPage=p;if(p==='dashboard')return dashboard();if(p==='assets')return assetsPage();if(p==='usage')return usagePage();if(p==='people')return peoplePage();if(p==='settings')return settingsPage();if(p==='maintenance')return foundation('ซ่อมบำรุง','Work Order, PM, Vendor/Workshop และค่าใช้จ่าย');if(p==='fuel')return foundation('เชื้อเพลิง/ค่าใช้จ่าย','Fuel Transaction, Expense Ledger และต้นทุนต่อ Asset');}
function selectNav(p){document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===p));navigate(p);}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>selectNav(b.dataset.page));
$('#backupBtn').onclick=backup;$('#restoreBtn').onclick=restore;modal.addEventListener('click',e=>{if(e.target===modal)closeModal();});
window.fleet.appInfo().then(i=>{$('#dbPath').textContent=i.dbPath||i.dataPath||'';});navigate('dashboard');
