const $=s=>document.querySelector(s);
const content=$('#content'), title=$('#pageTitle'), modal=$('#modal'), form=$('#usageForm');
let assets=[];
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmt=d=>d?new Date(d).toLocaleString('th-TH'):'-';

async function loadAssets(q=''){ assets=await window.fleet.listAssets(q); return assets; }
async function dashboard(){ const s=await window.fleet.dashboard(); title.textContent='ภาพรวม'; content.innerHTML=`<div class="cards"><div class="card"><span class="muted">ทรัพย์สินทั้งหมด</span><b>${s.assets}</b></div><div class="card"><span class="muted">พร้อมใช้งาน</span><b>${s.available}</b></div><div class="card"><span class="muted">รายการใช้งานที่ยังไม่ปิด</span><b>${s.usageOpen}</b></div><div class="card"><span class="muted">งานซ่อมที่ยังไม่ปิด</span><b>${s.maintenanceOpen}</b></div></div><div class="panel"><h3>Fleet Desktop v0.1.2</h3><p class="muted">ฐาน Desktop Offline สำหรับ Asset, Usage, Maintenance, Fuel/Cost และ HR Integration</p></div>`; }
async function assetsPage(){ title.textContent='ทรัพย์สิน'; await loadAssets(); const render=()=>{content.innerHTML=`<div class="panel"><div class="toolbar"><input id="assetSearch" placeholder="ค้นหารหัส ชื่อ หรือทะเบียน"><span class="muted">${assets.length} รายการ</span></div>${assets.length?`<table><thead><tr><th>รหัส</th><th>ชื่อ</th><th>ทะเบียน</th><th>ประเภท</th><th>สถานะ</th><th>เลขไมล์/ชั่วโมง</th></tr></thead><tbody>${assets.map(a=>`<tr><td>${esc(a.asset_code)}</td><td>${esc(a.name)}</td><td>${esc(a.registration_no||'-')}</td><td>${esc(a.asset_kind)}</td><td><span class="status">${esc(a.status)}</span></td><td>${esc(a.current_meter)} ${esc(a.current_meter_unit)}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">ยังไม่มีข้อมูลทรัพย์สิน</div>'}</div>`; $('#assetSearch').addEventListener('input',async e=>{await loadAssets(e.target.value);render();});}; render(); }
async function usagePage(){ title.textContent='การใช้รถ/เครื่องจักร'; const list=await window.fleet.listUsage(); content.innerHTML=`<div class="panel"><div class="toolbar"><div><b>คำขอและการใช้งาน</b><div class="muted">Offline admin workflow foundation</div></div><button class="primary" id="newUsage">+ บันทึกคำขอ</button></div>${list.length?`<table><thead><tr><th>เลขที่</th><th>ผู้ขอ</th><th>ช่วงเวลา</th><th>รถที่จัด</th><th>อนุมัติ</th><th>สถานะ</th></tr></thead><tbody>${list.map(u=>`<tr><td>${esc(u.request_no)}</td><td>${esc(u.requester_name)}</td><td>${fmt(u.planned_start_at)}<br>${fmt(u.planned_end_at)}</td><td>${esc(u.assigned_asset_code||'ยังไม่จัดสรร')}</td><td>${esc(u.approval_status)}</td><td><span class="status">${esc(u.usage_status)}</span></td></tr>`).join('')}</tbody></table>`:'<div class="empty">ยังไม่มีคำขอใช้รถ/เครื่องจักร</div>'}</div>`; $('#newUsage').onclick=openUsage; }
function foundation(name,desc){ title.textContent=name; content.innerHTML=`<div class="panel"><h3>${name}</h3><p>${desc}</p><p class="muted">v0.1.2 วาง Database Schema และ Architecture ไว้แล้ว แต่ยังไม่เปิด Workflow เต็ม</p></div>`; }
async function openUsage(){ await loadAssets(); const sel=$('#assetSelect'); sel.innerHTML='<option value="">ยังไม่จัดสรร</option>'+assets.filter(a=>a.status==='AVAILABLE').map(a=>`<option value="${esc(a.id)}">${esc(a.asset_code)} — ${esc(a.name)} ${a.registration_no?'('+esc(a.registration_no)+')':''}</option>`).join(''); modal.classList.remove('hidden'); }
function closeUsage(){ modal.classList.add('hidden'); form.reset(); }
form.addEventListener('submit',async e=>{ e.preventDefault(); const data=Object.fromEntries(new FormData(form)); await window.fleet.createUsage(data); closeUsage(); await usagePage(); });
$('#closeModal').onclick=closeUsage; $('#cancelModal').onclick=closeUsage;
$('#backupBtn').onclick=async()=>{ const r=await window.fleet.backup(); if(r?.ok) alert('สำรองข้อมูลแล้ว\n'+r.path); };
document.querySelectorAll('nav button').forEach(b=>b.onclick=async()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');const p=b.dataset.page;if(p==='dashboard')return dashboard();if(p==='assets')return assetsPage();if(p==='usage')return usagePage();if(p==='maintenance')return foundation('ซ่อมบำรุง','รองรับ Work Order, PM, Vendor/Workshop และเชื่อมค่าใช้จ่าย');if(p==='fuel')return foundation('เชื้อเพลิง/ค่าใช้จ่าย','รองรับ Fuel Transaction, Expense Ledger และต้นทุนต่อ Asset');if(p==='people')return foundation('พนักงานและผู้ใช้งาน','Person/Employee Master, User Account, Role, Permission, Data Scope และ HR Integration');return foundation('ตั้งค่า','Site/Device, Master Data, Backup/Restore และ Integration foundation');});
window.fleet.appInfo().then(i=>{$('#dbPath').textContent=i.dbPath||'';}); dashboard();
